/*
 * Copyright (c) 2007-2009, Osmorc Development Team
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright notice, this list
 *       of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright notice, this
 *       list of conditions and the following disclaimer in the documentation and/or other
 *       materials provided with the distribution.
 *     * Neither the name of 'Osmorc Development Team' nor the names of its contributors may be
 *       used to endorse or promote products derived from this software without specific
 *       prior written permission.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.osmorc.frameworkintegration.impl.equinox.ui;

import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.ui.IdeBorderFactory;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.NotNull;
import org.osmorc.frameworkintegration.impl.equinox.EquinoxRunProperties;
import org.osmorc.run.OsgiRunConfiguration;
import org.osmorc.run.ui.FrameworkRunPropertiesEditor;
import org.osmorc.run.ui.GenericRunPropertiesEditor;

import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;

/**
 * @author <a href="mailto:janthomae@janthomae.de">Jan Thomä</a>
 * @author <a href="mailto:robert@beeger.net">Robert F. Beeger</a>
 */
public class EquinoxRunPropertiesEditor implements FrameworkRunPropertiesEditor {
  private final JPanel myMainPanel;
  private final GenericRunPropertiesEditor myGenericRunPropertiesEditor;
  private final JRadioButton myJustTheBundlesRadioButton;
  private final JRadioButton myProductRadioButton;
  private final JTextField myProductTextField;
  private final JRadioButton myApplicationRadioButton;
  private final JTextField myApplicationTextField;

  public EquinoxRunPropertiesEditor() {
    {
      myGenericRunPropertiesEditor = new GenericRunPropertiesEditor();
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
      myMainPanel.add(myGenericRunPropertiesEditor.$$$getRootComponent$$$(),
                      new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0,
                                          false));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
      panel1.putClientProperty("BorderFactoryClass", "com.intellij.ui.IdeBorderFactory$PlainSmallWithIndent");
      myMainPanel.add(panel1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                  GridConstraints.SIZEPOLICY_WANT_GROW,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                                  null, 0, false));
      panel1.setBorder(IdeBorderFactory.PlainSmallWithIndent.createTitledBorder(BorderFactory.createEtchedBorder(),
                                                                                this.$$$getMessageFromBundle$$$("messages/OsmorcBundle",
                                                                                                                "run.configuration.form.equinox.group.run"),
                                                                                TitledBorder.DEFAULT_JUSTIFICATION,
                                                                                TitledBorder.DEFAULT_POSITION, null, null));
      myJustTheBundlesRadioButton = new JRadioButton();
      this.$$$loadButtonText$$$(myJustTheBundlesRadioButton,
                                this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "run.configuration.form.equinox.run.bundles"));
      panel1.add(myJustTheBundlesRadioButton, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                  GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                  null, null, null, 0, false));
      myProductRadioButton = new JRadioButton();
      this.$$$loadButtonText$$$(myProductRadioButton,
                                this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "run.configuration.form.equinox.run.product"));
      panel1.add(myProductRadioButton,
                 new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myProductTextField = new JTextField();
      panel1.add(myProductTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                         GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                         new Dimension(150, -1), null, 0, false));
      myApplicationRadioButton = new JRadioButton();
      this.$$$loadButtonText$$$(myApplicationRadioButton,
                                this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "run.configuration.form.equinox.run.app"));
      panel1.add(myApplicationRadioButton,
                 new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myApplicationTextField = new JTextField();
      panel1.add(myApplicationTextField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                             GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                             new Dimension(150, -1), null, 0, false));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      ButtonGroup buttonGroup;
      buttonGroup = new ButtonGroup();
      buttonGroup.add(myProductRadioButton);
      buttonGroup.add(myApplicationRadioButton);
      buttonGroup.add(myJustTheBundlesRadioButton);
    }
    ActionListener updater = new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        updatePresentation();
      }
    };
    myJustTheBundlesRadioButton.addActionListener(updater);
    myProductRadioButton.addActionListener(updater);
    myApplicationRadioButton.addActionListener(updater);
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  private void updatePresentation() {
    if (myJustTheBundlesRadioButton.isSelected()) {
      myProductTextField.setText("");
      myProductTextField.setEnabled(false);
      myApplicationTextField.setText("");
      myApplicationTextField.setEnabled(false);
    }
    else if (myProductRadioButton.isSelected()) {
      myApplicationTextField.setText("");
      myApplicationTextField.setEnabled(false);
      myProductTextField.setEnabled(true);
    }
    else if (myApplicationRadioButton.isSelected()) {
      myProductTextField.setText("");
      myProductTextField.setEnabled(false);
      myApplicationTextField.setEnabled(true);
    }
  }

  @Override
  public JPanel getUI() {
    return myMainPanel;
  }

  @Override
  public void resetEditorFrom(@NotNull OsgiRunConfiguration runConfiguration) {
    myGenericRunPropertiesEditor.resetEditorFrom(runConfiguration);

    Map<String, String> properties = runConfiguration.getAdditionalProperties();
    String product = EquinoxRunProperties.getEquinoxProduct(properties);
    String application = EquinoxRunProperties.getEquinoxApplication(properties);
    if (!StringUtil.isEmptyOrSpaces(product)) {
      myProductRadioButton.setSelected(true);
      myProductTextField.setText(product);
    }
    else if (!StringUtil.isEmptyOrSpaces(application)) {
      myApplicationRadioButton.setSelected(true);
      myApplicationTextField.setText(application);
    }
    else {
      myJustTheBundlesRadioButton.setSelected(true);
    }

    updatePresentation();
  }

  @Override
  public void applyEditorTo(@NotNull OsgiRunConfiguration runConfiguration) throws ConfigurationException {
    myGenericRunPropertiesEditor.applyEditorTo(runConfiguration);

    Map<String, String> properties = new HashMap<>();
    EquinoxRunProperties.setEquinoxProduct(properties, myProductTextField.getText());
    EquinoxRunProperties.setEquinoxApplication(properties, myApplicationTextField.getText());
    runConfiguration.putAdditionalProperties(properties);
  }
}
