/*
 * Copyright (c) 2007-2009, Osmorc Development Team
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright notice, this list
 *       of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright notice, this
 *       list of conditions and the following disclaimer in the documentation and/or other
 *       materials provided with the distribution.
 *     * Neither the name of 'Osmorc Development Team' nor the names of its contributors may be
 *       used to endorse or promote products derived from this software without specific
 *       prior written permission.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.osmorc.facet.ui;

import com.intellij.compiler.server.BuildManager;
import com.intellij.facet.ui.FacetEditorContext;
import com.intellij.facet.ui.FacetEditorTab;
import com.intellij.ide.util.ClassFilter;
import com.intellij.ide.util.TreeJavaClassChooserDialog;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.openapi.util.Disposer;
import com.intellij.psi.PsiClass;
import com.intellij.psi.search.GlobalSearchScope;
import com.intellij.ui.IdeBorderFactory;
import com.intellij.ui.UserActivityWatcher;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import org.jetbrains.annotations.NotNull;
import org.osmorc.facet.OsmorcFacetConfiguration;
import org.osmorc.i18n.OsmorcBundle;
import org.osmorc.settings.ManifestEditor;
import org.osmorc.util.OsgiPsiUtil;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import java.awt.BorderLayout;
import java.lang.reflect.Method;
import java.util.ResourceBundle;

/**
 * The facet editor tab which is used to set up Osmorc facet settings concerning the generation of the manifest file by
 * Osmorc.
 *
 * @author <a href="mailto:janthomae@janthomae.de">Jan Thomä</a>
 * @author <a href="mailto:robert@beeger.net">Robert F. Beeger</a>
 */
public class OsmorcFacetManifestGenerationEditorTab extends FacetEditorTab {
  private final FacetEditorContext myEditorContext;
  private final JPanel myRootPanel;
  private final JTextField myBundleSymbolicName;
  private final TextFieldWithBrowseButton myBundleActivator;
  private final JTextField myBundleVersion;
  private final JPanel myEditorPanel;
  private final ManifestEditor myAdditionalPropertiesEditor;
  private boolean myModified;

  public OsmorcFacetManifestGenerationEditorTab(FacetEditorContext editorContext) {
    myEditorContext = editorContext;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myRootPanel = new JPanel();
      myRootPanel.setLayout(new FormLayout("fill:d:grow", "center:271px:grow"));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow",
                                      "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(p;4px):grow"));
      panel1.putClientProperty("BorderFactoryClass", "com.intellij.ui.IdeBorderFactory$PlainSmallWithIndent");
      CellConstraints cc = new CellConstraints();
      myRootPanel.add(panel1, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
      panel1.setBorder(IdeBorderFactory.PlainSmallWithIndent.createTitledBorder(null,
                                                                                this.$$$getMessageFromBundle$$$("messages/OsmorcBundle",
                                                                                                                "facet.form.manifest.group.bundle"),
                                                                                TitledBorder.DEFAULT_JUSTIFICATION,
                                                                                TitledBorder.DEFAULT_POSITION, null, null));
      final JLabel label1 = new JLabel();
      this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "facet.form.manifest.bsn"));
      panel1.add(label1, cc.xy(1, 1));
      myBundleSymbolicName = new JTextField();
      panel1.add(myBundleSymbolicName, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
      final JLabel label2 = new JLabel();
      this.$$$loadLabelText$$$(label2, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "facet.form.manifest.activator"));
      panel1.add(label2, cc.xy(1, 3));
      myBundleActivator = new TextFieldWithBrowseButton();
      panel1.add(myBundleActivator, cc.xy(3, 3));
      final JLabel label3 = new JLabel();
      this.$$$loadLabelText$$$(label3, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "facet.form.manifest.version"));
      panel1.add(label3, cc.xy(1, 5));
      myBundleVersion = new JTextField();
      panel1.add(myBundleVersion, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
      final JLabel label4 = new JLabel();
      this.$$$loadLabelText$$$(label4, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "facet.form.manifest.additional"));
      label4.setVerticalAlignment(0);
      label4.setVerticalTextPosition(0);
      panel1.add(label4, cc.xy(1, 7, CellConstraints.DEFAULT, CellConstraints.TOP));
      myEditorPanel = new JPanel();
      myEditorPanel.setLayout(new BorderLayout(0, 0));
      panel1.add(myEditorPanel, cc.xy(3, 7, CellConstraints.FILL, CellConstraints.FILL));
      label1.setLabelFor(myBundleSymbolicName);
      label3.setLabelFor(myBundleVersion);
    }

    myAdditionalPropertiesEditor = new ManifestEditor(myEditorContext.getProject(), "");
    myAdditionalPropertiesEditor.setPreferredSize(myAdditionalPropertiesEditor.getComponent().getPreferredSize());
    myEditorPanel.add(myAdditionalPropertiesEditor, BorderLayout.CENTER);

    UserActivityWatcher watcher = new UserActivityWatcher();
    watcher.addUserActivityListener(() -> myModified = true);
    watcher.register(myRootPanel);

    myBundleActivator.addActionListener(e -> onBundleActivatorSelect());
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myRootPanel; }

  private void updateGui() {
    boolean isManuallyEdited = myEditorContext.getUserData(OsmorcFacetGeneralEditorTab.MANUAL_MANIFEST_EDITING_KEY) == Boolean.TRUE;
    boolean isToolGenerated = myEditorContext.getUserData(OsmorcFacetGeneralEditorTab.EXT_TOOL_MANIFEST_CREATION_KEY) == Boolean.TRUE;
    boolean enabled = !(isManuallyEdited || isToolGenerated);

    myBundleSymbolicName.setEnabled(enabled);
    myBundleActivator.setEnabled(enabled);
    myBundleVersion.setEnabled(enabled);
    myAdditionalPropertiesEditor.getComponent().setEnabled(enabled);
  }

  private void onBundleActivatorSelect() {
    Project project = myEditorContext.getProject();
    PsiClass activatorClass = OsgiPsiUtil.getActivatorClass(project);
    ClassFilter filter = new TreeJavaClassChooserDialog.InheritanceJavaClassFilterImpl(activatorClass, false, true, null);
    GlobalSearchScope scope = GlobalSearchScope.moduleWithDependenciesScope(myEditorContext.getModule());
    TreeJavaClassChooserDialog dialog =
      new TreeJavaClassChooserDialog(OsmorcBundle.message("facet.editor.select.bundle.activator"), project, scope, filter, null);
    dialog.showDialog();
    PsiClass psiClass = dialog.getSelected();
    if (psiClass != null) {
      myBundleActivator.setText(psiClass.getQualifiedName());
    }
  }

  @Override
  public String getDisplayName() {
    return OsmorcBundle.message("facet.tab.manifest");
  }

  @Override
  public @NotNull JComponent createComponent() {
    return myRootPanel;
  }

  @Override
  public boolean isModified() {
    return myModified;
  }

  @Override
  public void apply() {
    OsmorcFacetConfiguration configuration = (OsmorcFacetConfiguration)myEditorContext.getFacet().getConfiguration();
    configuration.setBundleActivator(myBundleActivator.getText());
    configuration.setBundleSymbolicName(myBundleSymbolicName.getText());
    configuration.setBundleVersion(myBundleVersion.getText());
    configuration.setAdditionalProperties(myAdditionalPropertiesEditor.getText());

    if (myModified) {
      BuildManager.getInstance().clearState(myEditorContext.getProject());
    }
    myModified = false;
  }

  @Override
  public void reset() {
    OsmorcFacetConfiguration configuration = (OsmorcFacetConfiguration)myEditorContext.getFacet().getConfiguration();
    myBundleActivator.setText(configuration.getBundleActivator());
    myBundleSymbolicName.setText(configuration.getBundleSymbolicName());
    myBundleVersion.setText(configuration.getBundleVersion());
    myAdditionalPropertiesEditor.setText(configuration.getAdditionalProperties());
    updateGui();
    myModified = false;
  }

  @Override
  public void onTabEntering() {
    super.onTabEntering();
    updateGui();
  }

  @Override
  public void disposeUIResources() {
    Disposer.dispose(myAdditionalPropertiesEditor);
  }

  @Override
  public String getHelpTopic() {
    return "reference.settings.module.facet.osgi";
  }
}
