/*
 * Copyright 2000-2005 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jetbrains.idea.perforce.application;

import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.project.Project;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jetbrains.idea.perforce.perforce.PerforceSettings;
import org.jetbrains.idea.perforce.perforce.connections.P4Connection;

import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.Insets;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

public class PerforceIntegratePanel implements PerforcePanel {
  private final JPanel myParticularConnectionsPanel;
  private final JPanel myPanel;

  private final JCheckBox myRunResolve;
  private final JCheckBox myRevertUnchanged;

  private final List<ParticularConnectionPerforceIntegratePanel> myConnectionPanels = new ArrayList<>();

  public PerforceIntegratePanel(Project project, List<? extends P4Connection> connections) {
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myPanel = new JPanel();
      myPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
      myRunResolve = new JCheckBox();
      this.$$$loadButtonText$$$(myRunResolve,
                                this.$$$getMessageFromBundle$$$("messages/PerforceBundle", "checkbox.run.resolve.after.sync"));
      myPanel.add(myRunResolve, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                    GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myRevertUnchanged = new JCheckBox();
      this.$$$loadButtonText$$$(myRevertUnchanged, this.$$$getMessageFromBundle$$$("messages/PerforceBundle",
                                                                                   "checkbox.update.options.revert.unchanged.files.before.sync"));
      myPanel.add(myRevertUnchanged, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                         GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                         GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myParticularConnectionsPanel = new JPanel();
      myParticularConnectionsPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
      myPanel.add(myParticularConnectionsPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                    GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                    GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }
    myParticularConnectionsPanel.setLayout(new GridLayout(0, 1));
    for (P4Connection p4Connection : connections) {
      final ParticularConnectionPerforceIntegratePanel panel = new ParticularConnectionPerforceIntegratePanel(project, p4Connection);
      myConnectionPanels.add(panel);
      myParticularConnectionsPanel.add(panel.getPanel());
    }
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myPanel; }

  @Override
  public void updateFrom(PerforceSettings settings) {
    myRevertUnchanged.setSelected(settings.INTEGRATE_REVERT_UNCHANGED);
    myRunResolve.setSelected(settings.INTEGRATE_RUN_RESOLVE);
    for (ParticularConnectionPerforceIntegratePanel panel : myConnectionPanels) {
      panel.updateFrom(settings);
    }
  }

  @Override
  public void applyTo(PerforceSettings settings) throws ConfigurationException {
    settings.INTEGRATE_REVERT_UNCHANGED = myRevertUnchanged.isSelected();
    settings.INTEGRATE_RUN_RESOLVE = myRunResolve.isSelected();
    for (ParticularConnectionPerforceIntegratePanel panel : myConnectionPanels) {
      panel.applyTo(settings);
    }
  }

  @Override
  public void cancel(PerforceSettings settings) {
    if (!isModified(settings)) {
      return;
    }

    settings.INTEGRATE_REVERT_UNCHANGED = myRevertUnchanged.isSelected();
    settings.INTEGRATE_RUN_RESOLVE = myRunResolve.isSelected();
    for (ParticularConnectionPerforceIntegratePanel panel : myConnectionPanels) {
      panel.cancel(settings);
    }
  }

  @Override
  public boolean isModified(PerforceSettings settings) {
    for (ParticularConnectionPerforceIntegratePanel panel : myConnectionPanels) {
      if (panel.isModified(settings)) {
        return true;
      }
    }
    return
      settings.INTEGRATE_REVERT_UNCHANGED != myRevertUnchanged.isSelected() ||
      settings.INTEGRATE_RUN_RESOLVE != myRunResolve.isSelected();
  }

  @Override
  public JPanel getPanel() {
    return myPanel;
  }
}
