// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.lang.javascript.flex.flashbuilder;

import com.intellij.lang.javascript.flex.FlexBundle;
import com.intellij.openapi.fileChooser.FileChooserDescriptorFactory;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.ui.LabeledComponentNoThrow;
import com.intellij.openapi.ui.Messages;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.openapi.util.io.FileUtil;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.JComponent;
import javax.swing.JPanel;
import java.awt.Dimension;
import java.awt.Insets;
import java.io.File;

public class AskPathDialog extends DialogWrapper {
  private final JPanel myMainPanel;
  private final LabeledComponentNoThrow<TextFieldWithBrowseButton> myPathComponent;

  protected AskPathDialog(final String title, final String label, final String initialPath) {
    super(true);
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      myPathComponent = new LabeledComponentNoThrow();
      myPathComponent.setComponentClass("com.intellij.openapi.ui.TextFieldWithBrowseButton");
      myPathComponent.setText("Multiple projects found. Extract them to respective subfolders of");
      myMainPanel.add(myPathComponent, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                           new Dimension(400, -1), null, null, 0, false));
    }
    setTitle(title);
    myPathComponent.setText(label);
    myPathComponent.getComponent().setText(FileUtil.toSystemDependentName(initialPath));
    myPathComponent.getComponent().addBrowseFolderListener(null, FileChooserDescriptorFactory.createSingleFolderDescriptor());
    init();
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  @Override
  protected JComponent createCenterPanel() {
    return myMainPanel;
  }

  @Override
  protected void doOKAction() {
    final File dir = new File(getPath());
    if (dir.isDirectory() && dir.list().length > 0) {
      if (Messages.YES !=
          Messages
            .showYesNoDialog(myMainPanel, FlexBundle.message("folder.not.empty", dir.getPath()), getTitle(), Messages.getWarningIcon())) {
        return;
      }
    }
    super.doOKAction();
  }

  public String getPath() {
    return FileUtil.toSystemIndependentName(myPathComponent.getComponent().getText().trim());
  }
}
