// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.lang.javascript.flex.debug;

import com.intellij.openapi.actionSystem.ActionUpdateThread;
import com.intellij.openapi.actionSystem.AnAction;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.actionSystem.CommonDataKeys;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.application.ModalityState;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.xdebugger.XDebugSession;
import com.intellij.xdebugger.XDebuggerManager;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import java.awt.Insets;

/**
 * @author Maxim.Mossienko
 */
public class SendCommandToDebuggerAction extends AnAction {
  @Override
  public void update(final @NotNull AnActionEvent e) {
    Project project = e.getData(CommonDataKeys.PROJECT);
    if (project == null) return;

    final boolean internal = ApplicationManager.getApplication().isInternal();
    e.getPresentation().setVisible(internal);
    e.getPresentation().setEnabled(internal && XDebuggerManager.getInstance(project).getCurrentSession() != null);
  }

  @Override
  public @NotNull ActionUpdateThread getActionUpdateThread() {
    return ActionUpdateThread.BGT;
  }

  @Override
  public void actionPerformed(final @NotNull AnActionEvent e) {
    Project project = e.getData(CommonDataKeys.PROJECT);
    if (project == null) return;

    final XDebugSession xDebugSession = XDebuggerManager.getInstance(project).getCurrentSession();
    new MyDialogWrapper(project, xDebugSession).show();
  }

  static class MyDialogWrapper extends DialogWrapper {
    private final XDebugSession session;
    private final JPanel myPanel;
    private final JTextArea myResultArea;
    private final JTextArea myCommandArea;

    protected MyDialogWrapper(Project project, final XDebugSession xDebugSession) {
      super(project, false);
      session = xDebugSession;
      {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        myPanel = new JPanel();
        myPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JBScrollPane jBScrollPane1 = new JBScrollPane();
        myPanel.add(jBScrollPane1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null,
                                                       null, null, 0, false));
        myResultArea = new JTextArea();
        myResultArea.setEditable(false);
        myResultArea.setText("");
        jBScrollPane1.setViewportView(myResultArea);
        final JBScrollPane jBScrollPane2 = new JBScrollPane();
        myPanel.add(jBScrollPane2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null,
                                                       null, null, 0, false));
        myCommandArea = new JTextArea();
        jBScrollPane2.setViewportView(myCommandArea);
        final JLabel label1 = new JLabel();
        label1.setText("Command");
        myPanel.add(label1,
                    new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                        GridConstraints.SIZEPOLICY_FIXED,
                                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Result");
        myPanel.add(label2,
                    new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                        GridConstraints.SIZEPOLICY_FIXED,
                                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        label2.setLabelFor(myResultArea);
      }
      setOKButtonText("Send");
      setTitle("Send Commands to Flex Debugger");
      setModal(false);
      init();
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() { return myPanel; }

    @Override
    protected String getDimensionServiceKey() {
      return "flex.debug.send.commands.to.flex.debugger.service.key";
    }

    @Override
    protected void doOKAction() {
      getOKAction().setEnabled(false);
      ((FlexDebugProcess)session.getDebugProcess()).sendCommand(
        new DebuggerCommand(myCommandArea.getText(), CommandOutputProcessingType.SPECIAL_PROCESSING) {
          @Override
          CommandOutputProcessingMode onTextAvailable(final @NonNls String s) {
            ApplicationManager.getApplication().invokeLater(() -> {
              myResultArea.setText(s);
              getOKAction().setEnabled(true);
            }, ModalityState.defaultModalityState());

            return CommandOutputProcessingMode.DONE;
          }
        }
      );
    }

    @Override
    protected JComponent createCenterPanel() {
      return myPanel;
    }
  }
}