// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.jetbrains.lang.dart.ide.actions;

import com.intellij.ide.util.PropertiesComponent;
import com.intellij.openapi.fileChooser.FileChooserDescriptorFactory;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.ui.TextComponentAccessor;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.openapi.ui.ValidationInfo;
import com.intellij.openapi.util.SystemInfo;
import com.intellij.openapi.util.io.FileUtil;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.openapi.wm.IdeFocusManager;
import com.intellij.ui.components.JBLabel;
import com.intellij.ui.components.JBRadioButton;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jetbrains.lang.dart.DartBundle;
import com.jetbrains.lang.dart.pubServer.DartWebdev;
import com.jetbrains.lang.dart.sdk.DartSdk;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.lang.reflect.Method;
import java.util.ResourceBundle;

public class DartPubBuildDialog extends DialogWrapper {

  private static final String DART_PUB_BUILD_MODE_KEY = "DART_PUB_BUILD_MODE";
  private static final String DART_PUB_CUSTOM_BUILD_MODE_KEY = "DART_PUB_CUSTOM_BUILD_MODE";

  private static final String RELEASE_MODE = "release";
  private static final String DEBUG_MODE = "debug";
  private static final String OTHER_MODE = "other";
  private static final String DEFAULT_MODE = RELEASE_MODE;

  private static final String DART_BUILD_INPUT_KEY = "DART_BUILD_INPUT_KEY";
  private static final String DEFAULT_INPUT_FOLDER = "web";
  private static final String DART_BUILD_OUTPUT_KEY = "DART_PUB_BUILD_OUTPUT_KEY"; // _PUB_ - for compatibility
  private static final String DEFAULT_OUTPUT_FOLDER = "build";

  private final JPanel myMainPanel;
  private final JPanel myBuildModePanel;
  private final JBRadioButton myReleaseRadioButton;
  private final JBRadioButton myDebugRadioButton;
  private final JBRadioButton myOtherRadioButton;
  private final JTextField myOtherModeTextField;

  private final JPanel myInputFolderPanel;
  private final JTextField myInputFolderTextField;

  private final TextFieldWithBrowseButton myOutputFolderField;

  private final @NotNull Project myProject;
  private final boolean myUseWebdev;

  public DartPubBuildDialog(final @NotNull Project project, final @NotNull VirtualFile packageDir) {
    super(project);
    myProject = project;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      final JBLabel jBLabel1 = new JBLabel();
      this.$$$loadLabelText$$$(jBLabel1, this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.build.dialog.label.output.folder"));
      myMainPanel.add(jBLabel1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                    GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                    false));
      myOutputFolderField = new TextFieldWithBrowseButton();
      myMainPanel.add(myOutputFolderField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                               GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                               new Dimension(250, -1), null, null, 0, false));
      myBuildModePanel = new JPanel();
      myBuildModePanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
      myMainPanel.add(myBuildModePanel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            null, null, null, 0, true));
      final JBLabel jBLabel2 = new JBLabel();
      this.$$$loadLabelText$$$(jBLabel2, this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.build.dialog.label.build.mode"));
      myBuildModePanel.add(jBLabel2, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                         GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                         null, 0, false));
      myDebugRadioButton = new JBRadioButton();
      this.$$$loadButtonText$$$(myDebugRadioButton,
                                this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.build.dialog.radio.button.debug"));
      myBuildModePanel.add(myDebugRadioButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                   GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                   null, null, null, 1, false));
      myOtherRadioButton = new JBRadioButton();
      this.$$$loadButtonText$$$(myOtherRadioButton,
                                this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.build.dialog.radio.button.other"));
      myBuildModePanel.add(myOtherRadioButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                   GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                   null, null, null, 1, false));
      myOtherModeTextField = new JTextField();
      myBuildModePanel.add(myOtherModeTextField,
                           new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                               GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                               new Dimension(150, -1), null, 0, false));
      final Spacer spacer2 = new Spacer();
      myBuildModePanel.add(spacer2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                        GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 10), new Dimension(-1, 10),
                                                        new Dimension(-1, 10), 0, false));
      myReleaseRadioButton = new JBRadioButton();
      myReleaseRadioButton.setSelected(true);
      this.$$$loadButtonText$$$(myReleaseRadioButton,
                                this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.build.dialog.radio.button.release"));
      myBuildModePanel.add(myReleaseRadioButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                     GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                     GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                     null, null, null, 1, false));
      myInputFolderPanel = new JPanel();
      myInputFolderPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
      myMainPanel.add(myInputFolderPanel, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                              GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                              GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                              null, null, null, 0, true));
      final JBLabel jBLabel3 = new JBLabel();
      this.$$$loadLabelText$$$(jBLabel3, this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.build.dialog.label.input.folder"));
      myInputFolderPanel.add(jBLabel3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                           GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                           null, 0, false));
      myInputFolderTextField = new JTextField();
      myInputFolderPanel.add(myInputFolderTextField,
                             new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                 GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                 new Dimension(150, -1), null, 0, false));
      jBLabel1.setLabelFor(myOutputFolderField);
      jBLabel3.setLabelFor(myInputFolderTextField);
      ButtonGroup buttonGroup;
      buttonGroup = new ButtonGroup();
      buttonGroup.add(myReleaseRadioButton);
      buttonGroup.add(myDebugRadioButton);
      buttonGroup.add(myOtherRadioButton);
    }

    myUseWebdev = DartWebdev.INSTANCE.useWebdev(DartSdk.getDartSdk(project));
    setTitle(DartBundle.message(myUseWebdev ? "dart.webdev.build.title" : "dart.pub.build.title"));
    setOKButtonText(DartBundle.message("button.text.build2"));

    final ActionListener listener = e -> updateControls();
    myReleaseRadioButton.addActionListener(listener);
    myDebugRadioButton.addActionListener(listener);
    myOtherRadioButton.addActionListener(listener);
    myOtherRadioButton.addActionListener(e -> {
      if (myOtherRadioButton.isSelected()) {
        IdeFocusManager.getInstance(myProject).requestFocus(myOtherModeTextField, true);
      }
    });

    var packagePathSlash = FileUtil.toSystemDependentName(packageDir.getPath() + "/");
    myOutputFolderField.addBrowseFolderListener(
      myProject,
      FileChooserDescriptorFactory.createSingleFolderDescriptor().withTitle(DartBundle.message("button.browse.dialog.title.output.folder")),
      new TextComponentAccessor<>() {
        @Override
        public String getText(JTextField component) {
          final String path = component.getText();
          if (SystemInfo.isWindows && FileUtil.isWindowsAbsolutePath(path) || !SystemInfo.isWindows && FileUtil.isUnixAbsolutePath(path)) {
            return path;
          }
          return packagePathSlash + path;
        }

        @Override
        public void setText(JTextField component, @NotNull String text) {
          if (text.startsWith(packagePathSlash) && !text.equals(packagePathSlash)) {
            component.setText(text.substring(packagePathSlash.length()));
          }
          else {
            component.setText(text);
          }
        }
      });

    reset();
    init();
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  private void reset() {
    final PropertiesComponent propertiesComponent = PropertiesComponent.getInstance(myProject);

    if (myUseWebdev) {
      myBuildModePanel.setVisible(false);
      myInputFolderTextField.setText(propertiesComponent.getValue(DART_BUILD_INPUT_KEY, DEFAULT_INPUT_FOLDER));
    }
    else {
      myInputFolderPanel.setVisible(false);

      final String mode = propertiesComponent.getValue(DART_PUB_BUILD_MODE_KEY, DEFAULT_MODE);
      if (mode.equals(RELEASE_MODE)) {
        myReleaseRadioButton.setSelected(true);
      }
      else if (mode.equals(DEBUG_MODE)) {
        myDebugRadioButton.setSelected(true);
      }
      else {
        myOtherRadioButton.setSelected(true);
      }

      myOtherModeTextField.setText(propertiesComponent.getValue(DART_PUB_CUSTOM_BUILD_MODE_KEY, ""));
    }

    myOutputFolderField.setText(propertiesComponent.getValue(DART_BUILD_OUTPUT_KEY, DEFAULT_OUTPUT_FOLDER));

    updateControls();
  }

  private void updateControls() {
    myOtherModeTextField.setEnabled(myOtherRadioButton.isSelected());
  }

  @Override
  protected @Nullable JComponent createCenterPanel() {
    return myMainPanel;
  }

  @Override
  public @Nullable JComponent getPreferredFocusedComponent() {
    if (myOtherRadioButton.isSelected()) return myOtherModeTextField;
    return null;
  }

  @Override
  protected @Nullable ValidationInfo doValidate() {
    if (!myUseWebdev && myOtherRadioButton.isSelected() && StringUtil.isEmptyOrSpaces(myOtherModeTextField.getText())) {
      return new ValidationInfo(DartBundle.message("validation.info.build.mode.not.specified"));
    }

    if (myUseWebdev && myInputFolderTextField.getText().trim().isEmpty()) {
      return new ValidationInfo(DartBundle.message("validation.info.input.folder.not.specified"));
    }

    if (myOutputFolderField.getText().trim().isEmpty()) {
      return new ValidationInfo(DartBundle.message("validation.info.output.folder.not.specified"));
    }

    if (myUseWebdev && myInputFolderTextField.getText().trim().equals(myOutputFolderField.getText().trim())) {
      return new ValidationInfo(DartBundle.message("validation.info.input.and.output.folders.must.be.different"));
    }

    return null;
  }

  @Override
  protected void doOKAction() {
    saveDialogState();
    super.doOKAction();
  }

  private void saveDialogState() {
    final PropertiesComponent propertiesComponent = PropertiesComponent.getInstance(myProject);

    if (myUseWebdev) {
      final String inputPath = StringUtil.nullize(myInputFolderTextField.getText().trim());
      propertiesComponent.setValue(DART_BUILD_INPUT_KEY, inputPath, DEFAULT_INPUT_FOLDER);
    }
    else {
      final String mode = myReleaseRadioButton.isSelected() ? RELEASE_MODE
                                                            : myDebugRadioButton.isSelected() ? DEBUG_MODE
                                                                                              : OTHER_MODE;
      propertiesComponent.setValue(DART_PUB_BUILD_MODE_KEY, mode, DEFAULT_MODE);

      if (myOtherRadioButton.isSelected()) {
        propertiesComponent.setValue(DART_PUB_CUSTOM_BUILD_MODE_KEY, myOtherModeTextField.getText().trim());
      }
    }

    final String outputPath = StringUtil.nullize(myOutputFolderField.getText().trim());
    propertiesComponent.setValue(DART_BUILD_OUTPUT_KEY, outputPath, DEFAULT_OUTPUT_FOLDER);
  }

  public @NotNull String getPubBuildMode() {
    if (myReleaseRadioButton.isSelected()) return RELEASE_MODE;
    if (myDebugRadioButton.isSelected()) return DEBUG_MODE;
    return myOtherModeTextField.getText().trim();
  }

  public @NotNull String getInputFolder() {
    String path = myInputFolderTextField.getText().trim();
    if (path.isEmpty()) path = DEFAULT_INPUT_FOLDER;
    return path;
  }

  public @NotNull String getOutputFolder() {
    String path = myOutputFolderField.getText().trim();
    if (path.isEmpty()) path = DEFAULT_OUTPUT_FOLDER;
    return path;
  }
}
