/*
 * Copyright (c) 2007-2009, Osmorc Development Team
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright notice, this list
 *       of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright notice, this
 *       list of conditions and the following disclaimer in the documentation and/or other
 *       materials provided with the distribution.
 *     * Neither the name of 'Osmorc Development Team' nor the names of its contributors may be
 *       used to endorse or promote products derived from this software without specific
 *       prior written permission.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.osmorc.settings;

import com.intellij.ide.IdeBundle;
import com.intellij.openapi.actionSystem.ActionUpdateThread;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.project.DumbAwareAction;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.util.Disposer;
import com.intellij.ui.AnActionButton;
import com.intellij.ui.AnActionButtonRunnable;
import com.intellij.ui.CollectionListModel;
import com.intellij.ui.GuiUtils;
import com.intellij.ui.JBSplitter;
import com.intellij.ui.ListUtil;
import com.intellij.ui.ToolbarDecorator;
import com.intellij.ui.components.JBLabel;
import com.intellij.ui.components.JBList;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.PlatformIcons;
import com.intellij.util.ui.UIUtil;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.osgi.jps.model.LibraryBundlificationRule;

import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Insets;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

/**
 * @author <a href="mailto:janthomae@janthomae.de">Jan Thomä</a>
 */
public class LibraryBundlingEditorComponent {
  private final JPanel myMainPanel;
  private final JPanel myRulesPanel;
  private final JBList<LibraryBundlificationRule> myRulesList;
  private final JTextField myLibraryRegex;
  private final ManifestEditor myManifestEditor;
  private final JCheckBox myNeverBundle;
  private final JCheckBox myStopAfterThisRule;

  private final CollectionListModel<LibraryBundlificationRule> myRulesModel;
  private int myLastSelected = -1;

  public LibraryBundlingEditorComponent(@NotNull Project project) {
    {
      myManifestEditor = new ManifestEditor(project, "");
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
      final JSplitPane splitPane1 = new JSplitPane();
      myMainPanel.add(splitPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                      GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                      GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                      new Dimension(200, 200), null, 0, false));
      myRulesPanel = new JPanel();
      myRulesPanel.setLayout(new BorderLayout(0, 0));
      splitPane1.setLeftComponent(myRulesPanel);
      myRulesList = new JBList();
      myRulesList.setSelectionMode(0);
      myRulesPanel.add(myRulesList, BorderLayout.CENTER);
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
      splitPane1.setRightComponent(panel1);
      final JBLabel jBLabel1 = new JBLabel();
      this.$$$loadLabelText$$$(jBLabel1, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.app.form.name.pattern"));
      panel1.add(jBLabel1,
                 new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myLibraryRegex = new JTextField();
      panel1.add(myLibraryRegex, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                     GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                     new Dimension(150, -1), null, 0, false));
      final JBLabel jBLabel2 = new JBLabel();
      this.$$$loadLabelText$$$(jBLabel2, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.app.form.mf.entries"));
      panel1.add(jBLabel2,
                 new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      panel1.add(myManifestEditor, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                       new Dimension(-1, 200), null, 0, false));
      myNeverBundle = new JCheckBox();
      this.$$$loadButtonText$$$(myNeverBundle, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.app.form.ignore"));
      panel1.add(myNeverBundle, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                    GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myStopAfterThisRule = new JCheckBox();
      this.$$$loadButtonText$$$(myStopAfterThisRule, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.app.form.abort"));
      panel1.add(myStopAfterThisRule, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                          GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer1 = new Spacer();
      panel1.add(spacer1, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                              GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      jBLabel1.setLabelFor(myLibraryRegex);
    }
    GuiUtils.replaceJSplitPaneWithIDEASplitter(myMainPanel);
    ((JBSplitter)myMainPanel.getComponent(0)).setProportion(0.4f);

    myRulesPanel.add(
      ToolbarDecorator.createDecorator(myRulesList)
        .setAddAction(new AnActionButtonRunnable() {
          @Override
          public void run(AnActionButton button) {
            updateCurrentRule();
            myRulesModel.add(new LibraryBundlificationRule());
            myRulesList.setSelectedIndex(myRulesModel.getSize() - 1);
            updateFields();
          }
        })
        .setRemoveAction(new AnActionButtonRunnable() {
          @Override
          public void run(AnActionButton button) {
            myLastSelected = -1;
            if (myRulesModel.getSize() == 1) {
              myRulesModel.setElementAt(new LibraryBundlificationRule(), 0);
              myRulesList.setSelectedIndex(0);
            }
            else {
              int index = myRulesList.getSelectedIndex();
              myRulesModel.remove(index);
              myRulesList.setSelectedIndex(index > 0 ? index - 1 : 0);
            }
            updateFields();
          }
        })
        .setMoveUpAction(new AnActionButtonRunnable() {
          @Override
          public void run(AnActionButton button) {
            updateCurrentRule();
            myLastSelected = -1;
            ListUtil.moveSelectedItemsUp(myRulesList);
            updateFields();
          }
        })
        .setMoveDownAction(new AnActionButtonRunnable() {
          @Override
          public void run(AnActionButton button) {
            updateCurrentRule();
            myLastSelected = -1;
            ListUtil.moveSelectedItemsDown(myRulesList);
            updateFields();
          }
        })
        .addExtraAction(new DumbAwareAction(IdeBundle.message("button.copy"), null, PlatformIcons.COPY_ICON) {
          @Override
          public void actionPerformed(@NotNull AnActionEvent e) {
            updateCurrentRule();
            int index = myRulesList.getSelectedIndex();
            if (index >= 0) {
              myRulesModel.add(myRulesModel.getElementAt(index).copy());
              myRulesList.setSelectedIndex(myRulesModel.getSize() - 1);
              updateFields();
            }
          }

          @Override
          public void update(@NotNull AnActionEvent e) {
            e.getPresentation().setEnabled(myRulesList.getSelectedIndex() >= 0);
          }

          @Override
          public @NotNull ActionUpdateThread getActionUpdateThread() {
            return ActionUpdateThread.EDT;
          }
        })
        .createPanel(), BorderLayout.CENTER
    );

    myRulesModel = new CollectionListModel<>();
    myRulesList.setModel(myRulesModel);
    myRulesList.addListSelectionListener(new ListSelectionListener() {
      @Override
      public void valueChanged(ListSelectionEvent e) {
        updateCurrentRule();
        updateFields();
      }
    });
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  private void updateFields() {
    int index = myRulesList.getSelectedIndex();
    if (index >= 0 && index != myLastSelected) {
      final LibraryBundlificationRule rule = myRulesModel.getElementAt(index);
      myLibraryRegex.setText(rule.getRuleRegex());
      UIUtil.invokeLaterIfNeeded(() -> myManifestEditor.setText(rule.getAdditionalProperties()));
      myNeverBundle.setSelected(rule.isDoNotBundle());
      myStopAfterThisRule.setSelected(rule.isStopAfterThisRule());
      myLastSelected = index;
    }
    myLibraryRegex.setEnabled(index >= 0);
    myManifestEditor.setEnabled(index >= 0);
    myNeverBundle.setEnabled(index >= 0);
    myStopAfterThisRule.setEnabled(index >= 0);
  }

  private void updateCurrentRule() {
    if (myLastSelected >= 0 && myLastSelected < myRulesModel.getSize()) {
      LibraryBundlificationRule newRule = new LibraryBundlificationRule();
      newRule.setRuleRegex(myLibraryRegex.getText().trim());
      newRule.setAdditionalProperties(myManifestEditor.getText().trim());
      newRule.setDoNotBundle(myNeverBundle.isSelected());
      newRule.setStopAfterThisRule(myStopAfterThisRule.isSelected());
      if (!newRule.equals(myRulesModel.getElementAt(myLastSelected))) {
        myRulesModel.setElementAt(newRule, myLastSelected);
      }
    }
  }

  public JPanel getMainPanel() {
    return myMainPanel;
  }

  public void dispose() {
    Disposer.dispose(myManifestEditor);
  }

  public boolean isModified(ApplicationSettings settings) {
    updateCurrentRule();
    List<LibraryBundlificationRule> rules = settings.getLibraryBundlificationRules();
    if (myRulesModel.getSize() != rules.size()) {
      return true;
    }
    for (int i = 0; i < rules.size(); i++) {
      if (!rules.get(i).equals(myRulesModel.getElementAt(i))) {
        return true;
      }
    }
    return false;
  }

  public void resetTo(ApplicationSettings settings) {
    myLastSelected = -1;
    myRulesModel.replaceAll(settings.getLibraryBundlificationRules());
    myRulesList.setSelectedIndex(0);
    updateFields();
  }

  public void applyTo(ApplicationSettings settings) throws ConfigurationException {
    updateCurrentRule();

    for (int i = 0; i < myRulesModel.getSize(); i++) {
      try {
        myRulesModel.getElementAt(i).validate();
      }
      catch (IllegalArgumentException e) {
        myRulesList.setSelectedIndex(i);
        throw new ConfigurationException(e.getMessage());
      }
    }

    settings.setLibraryBundlificationRules(new ArrayList<>(myRulesModel.getItems()));
  }
}
