/*
 * Copyright (c) 2007-2009, Osmorc Development Team
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright notice, this list
 *       of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright notice, this
 *       list of conditions and the following disclaimer in the documentation and/or other
 *       materials provided with the distribution.
 *     * Neither the name of 'Osmorc Development Team' nor the names of its contributors may be
 *       used to endorse or promote products derived from this software without specific
 *       prior written permission.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.osmorc.settings;

import com.intellij.openapi.application.WriteAction;
import com.intellij.openapi.fileChooser.FileChooser;
import com.intellij.openapi.fileChooser.FileChooserDescriptorFactory;
import com.intellij.openapi.module.Module;
import com.intellij.openapi.module.ModuleManager;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.project.ProjectUtil;
import com.intellij.openapi.ui.ComboBox;
import com.intellij.openapi.ui.Messages;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.openapi.vfs.LocalFileSystem;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.ui.UserActivityWatcher;
import com.intellij.ui.components.JBCheckBox;
import com.intellij.ui.components.JBLabel;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ui.UIUtil;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.osgi.jps.model.OutputPathType;
import org.osmorc.facet.OsmorcFacet;
import org.osmorc.facet.OsmorcFacetConfiguration;
import org.osmorc.frameworkintegration.FrameworkInstanceDefinition;
import org.osmorc.i18n.OsmorcBundle;
import org.osmorc.util.FrameworkInstanceRenderer;

import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Insets;
import java.lang.reflect.Method;
import java.util.List;
import java.util.Objects;
import java.util.ResourceBundle;

/**
 * @author <a href="mailto:janthomae@janthomae.de">Jan Thomä</a>
 */
public class ProjectSettingsEditorComponent {
  private UserActivityWatcher myWatcher;
  private final JPanel myMainPanel;
  private final JComboBox<FrameworkInstanceDefinition> myFrameworkInstance;
  private final ComboBox<String> myDefaultManifestFileLocation;
  private final TextFieldWithBrowseButton myBundleOutputPath;
  private final JButton myApplyToAllButton;
  private final JBCheckBox myBndAutoImport;

  private final Project myProject;
  private ProjectSettings mySettings;
  private boolean myModified;

  public ProjectSettingsEditorComponent(Project project) {
    myProject = project;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
      final JLabel label1 = new JLabel();
      this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.project.form.framework"));
      myMainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, 1,
                                                  GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myFrameworkInstance = new JComboBox();
      myMainPanel.add(myFrameworkInstance, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                               GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, 0));
      myMainPanel.add(panel1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                                  null, 0, true));
      final JLabel label2 = new JLabel();
      this.$$$loadLabelText$$$(label2, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.project.form.manifest"));
      panel1.add(label2,
                 new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     1, null, null, null, 0, false));
      myDefaultManifestFileLocation = new ComboBox();
      panel1.add(myDefaultManifestFileLocation,
                 new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                     GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JBLabel jBLabel1 = new JBLabel();
      jBLabel1.setComponentStyle(UIUtil.ComponentStyle.SMALL);
      jBLabel1.setFontColor(UIUtil.FontColor.BRIGHTER);
      this.$$$loadLabelText$$$(jBLabel1, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.project.form.manifest.path"));
      panel1.add(jBLabel1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, 1,
                                               GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
      final JPanel panel2 = new JPanel();
      panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, 0));
      myMainPanel.add(panel2, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                                  null, 0, true));
      final JBLabel jBLabel2 = new JBLabel();
      this.$$$loadLabelText$$$(jBLabel2, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.project.form.output"));
      panel2.add(jBLabel2,
                 new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     1, null, null, null, 0, false));
      final JBLabel jBLabel3 = new JBLabel();
      jBLabel3.setComponentStyle(UIUtil.ComponentStyle.SMALL);
      jBLabel3.setFontColor(UIUtil.FontColor.BRIGHTER);
      this.$$$loadLabelText$$$(jBLabel3, this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.project.form.output.common"));
      panel2.add(jBLabel3, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, 1,
                                               GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
      final JPanel panel3 = new JPanel();
      panel3.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
      panel2.add(panel3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                             GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                             GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null,
                                             0, false));
      myBundleOutputPath = new TextFieldWithBrowseButton();
      panel3.add(myBundleOutputPath, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                         GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                         GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myApplyToAllButton = new JButton();
      this.$$$loadButtonText$$$(myApplyToAllButton,
                                this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.project.form.apply.to.all"));
      myApplyToAllButton.setToolTipText(this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.project.form.apply.to.all.tt"));
      panel3.add(myApplyToAllButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, 1,
                                                         GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myBndAutoImport = new JBCheckBox();
      this.$$$loadButtonText$$$(myBndAutoImport,
                                this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.project.form.auto.import"));
      myBndAutoImport.setToolTipText(this.$$$getMessageFromBundle$$$("messages/OsmorcBundle", "settings.project.form.auto.import.tt"));
      myMainPanel.add(myBndAutoImport, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                           GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                           null, 0, false));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      label1.setLabelFor(myFrameworkInstance);
      label2.setLabelFor(myDefaultManifestFileLocation);
    }

    myFrameworkInstance.setRenderer(new FrameworkInstanceRenderer('[' + OsmorcBundle.message("framework.not.specified") + ']') {
      private final List<FrameworkInstanceDefinition> myActiveInstances =
        ApplicationSettings.getInstance().getActiveFrameworkInstanceDefinitions();

      @Override
      protected boolean isInstanceDefined(@NotNull FrameworkInstanceDefinition instance) {
        return myActiveInstances.contains(instance);
      }
    });

    myWatcher = new UserActivityWatcher();
    myWatcher.register(myMainPanel);
    myWatcher.addUserActivityListener(() -> myModified = true);

    myDefaultManifestFileLocation.setEditable(true);
    myDefaultManifestFileLocation.addItem("META-INF"); //NON-NLS

    myBundleOutputPath.addActionListener((e) -> {
      VirtualFile preselect = LocalFileSystem.getInstance().findFileByPath(myBundleOutputPath.getText());
      if (preselect == null) preselect = ProjectUtil.guessProjectDir(myProject);
      VirtualFile virtualFile = FileChooser.chooseFile(FileChooserDescriptorFactory.createSingleFolderDescriptor(), myProject, preselect);
      if (virtualFile != null) {
        myBundleOutputPath.setText(virtualFile.getPath());
      }
    });

    myApplyToAllButton.addActionListener((e) -> {
      WriteAction.run(() -> {
        for (Module module : ModuleManager.getInstance(myProject).getModules()) {
          OsmorcFacet facet = OsmorcFacet.getInstance(module);
          if (facet != null) {
            OsmorcFacetConfiguration configuration = facet.getConfiguration();
            configuration.setJarFileLocation(configuration.getJarFileName(), OutputPathType.OsgiOutputPath);
          }
        }
      });

      Messages.showInfoMessage(myProject, OsmorcBundle.message("settings.path.applied.text"),
                               OsmorcBundle.message("settings.path.applied.title"));
    });
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  public void dispose() {
    myWatcher = null;
  }

  public JPanel getMainPanel() {
    return myMainPanel;
  }

  public void applyTo(ProjectSettings settings) {
    String fileLocation = (String)myDefaultManifestFileLocation.getSelectedItem();
    if (fileLocation != null) {
      settings.setDefaultManifestFileLocation(fileLocation);
    }

    FrameworkInstanceDefinition instance = (FrameworkInstanceDefinition)myFrameworkInstance.getSelectedItem();
    settings.setFrameworkInstanceName(instance != null ? instance.getName() : null);

    String outputPath = myBundleOutputPath.getText();
    settings.setBundlesOutputPath(!StringUtil.isEmptyOrSpaces(outputPath) ? outputPath : null);

    settings.setBndAutoImport(myBndAutoImport.isSelected());

    myModified = false;
  }

  public void resetTo(ProjectSettings settings) {
    mySettings = settings;

    refreshFrameworkInstanceCombobox();

    myDefaultManifestFileLocation.setSelectedItem(mySettings.getDefaultManifestFileLocation());

    String bundlesPath = mySettings.getBundlesOutputPath();
    myBundleOutputPath.setText(Objects.requireNonNullElseGet(bundlesPath, () -> ProjectSettings.getDefaultBundlesOutputPath(myProject)));

    myBndAutoImport.setSelected(settings.isBndAutoImport());

    myModified = false;
  }

  private void refreshFrameworkInstanceCombobox() {
    myFrameworkInstance.removeAllItems();
    myFrameworkInstance.addItem(null);

    String frameworkInstanceName = mySettings.getFrameworkInstanceName();

    FrameworkInstanceDefinition projectFrameworkInstance = null;
    for (FrameworkInstanceDefinition instanceDefinition : ApplicationSettings.getInstance().getActiveFrameworkInstanceDefinitions()) {
      myFrameworkInstance.addItem(instanceDefinition);
      if (instanceDefinition.getName().equals(frameworkInstanceName)) {
        projectFrameworkInstance = instanceDefinition;
      }
    }

    // add it, but it will be marked red.
    if (projectFrameworkInstance == null && frameworkInstanceName != null) {
      projectFrameworkInstance = new FrameworkInstanceDefinition();
      projectFrameworkInstance.setName(frameworkInstanceName);
      myFrameworkInstance.addItem(projectFrameworkInstance);
    }
    myFrameworkInstance.setSelectedItem(projectFrameworkInstance);
  }

  public boolean isModified() {
    return myModified;
  }
}
