// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.lang.javascript.ui.newclass;

import com.intellij.ide.wizard.AbstractWizardStepEx;
import com.intellij.ide.wizard.CommitStepException;
import com.intellij.lang.javascript.JavaScriptBundle;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.ui.TableUtil;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.ui.table.TableView;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.util.containers.ContainerUtil;
import com.intellij.util.ui.ColumnInfo;
import com.intellij.util.ui.JBUI;
import com.intellij.util.ui.ListTableModel;
import com.intellij.util.ui.UIUtil;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Insets;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;

public class CustomVariablesStep extends AbstractWizardStepEx {

  private static final class Item {
    private final String name;
    private String value;

    private Item(final String name, final String value) {
      this.name = name;
      this.value = value;
    }
  }

  static final Object ID = new Object();
  private final WizardModel myModel;
  private final TableView<Item> myTable;
  private final JPanel myPanel;
  private final JLabel myTitleLabel;

  private static final ColumnInfo<Item, String> NAME = new ColumnInfo<>(JavaScriptBundle.message("varible.name.column.title")) {
    @Override
    public @Nullable String valueOf(final Item item) {
      return item.name;
    }
  };

  private static final ColumnInfo<Item, String> VALUE = new ColumnInfo<>(JavaScriptBundle.message("varible.value.column.title")) {
    @Override
    public @Nullable String valueOf(final Item item) {
      return item.value;
    }

    @Override
    public boolean isCellEditable(final Item item) {
      return true;
    }

    @Override
    public void setValue(final Item item, final String value) {
      item.value = value;
    }
  };

  public CustomVariablesStep(WizardModel model) {
    super(null);
    myModel = model;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myPanel = new JPanel();
      myPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
      myTitleLabel = new JLabel();
      this.$$$loadLabelText$$$(myTitleLabel, this.$$$getMessageFromBundle$$$("messages/JavaScriptBundle", "custom.template.variables"));
      myPanel.add(myTitleLabel,
                  new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                      GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JBScrollPane jBScrollPane1 = new JBScrollPane();
      myPanel.add(jBScrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                     GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                     GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                     null, null, 0, false));
      myTable = new TableView();
      jBScrollPane1.setViewportView(myTable);
      myTitleLabel.setLabelFor(jBScrollPane1);
    }
    myTable.setPreferredScrollableViewportSize(JBUI.size(100, -1));
    myTable.setVisibleRowCount(3);
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myPanel; }

  @Override
  public @NotNull Object getStepId() {
    return ID;
  }

  @Override
  public @Nullable Object getNextStepId() {
    return null;
  }

  @Override
  public @Nullable Object getPreviousStepId() {
    return MainStep.ID;
  }

  @Override
  public boolean isComplete() {
    return true;
  }

  @Override
  public void _init() {
    String text = JavaScriptBundle.message("custom.variables.step.title.label.text", myModel.getTemplateName());
    myTitleLabel.setText(UIUtil.removeMnemonic(text));
    myTitleLabel.setDisplayedMnemonic(text.charAt(UIUtil.getDisplayMnemonicIndex(text) + 1));

    ListTableModel<Item> model = new ListTableModel<>(NAME, VALUE);
    List<Item> items = ContainerUtil.sorted(
      ContainerUtil.map(myModel.getCustomTemplateAttributes(myModel.getTemplateName()).entrySet(), e -> new Item(e.getKey(), e.getValue())),
      (o1, o2) -> StringUtil.naturalCompare(o1.name, o2.name));
    model.addRows(items);
    myTable.setModelAndUpdateColumns(model);
  }

  @Override
  public void commit(final CommitType commitType) throws CommitStepException {
    TableUtil.stopEditing(myTable);
    List<Item> items = ((ListTableModel)myTable.getModel()).getItems();
    Map<String, String> map = new HashMap<>();
    for (Item item : items) {
      map.put(item.name, item.value);
    }
    myModel.setCustomTemplateAttributes(myModel.getTemplateName(), map);
  }

  @Override
  public JComponent getComponent() {
    return myPanel;
  }

  @Override
  public @Nullable JComponent getPreferredFocusedComponent() {
    return null;
  }

  public void shown() {
    TableUtil.editCellAt(myTable, 0, 1);
  }
}
