package com.intellij.lang.javascript.flex.projectStructure.ui;

import com.intellij.flex.model.bc.BuildConfigurationNature;
import com.intellij.flex.model.bc.OutputType;
import com.intellij.flex.model.bc.TargetPlatform;
import com.intellij.ide.ui.UISettings;
import com.intellij.lang.javascript.flex.FlexBundle;
import com.intellij.lang.javascript.flex.projectStructure.options.BCUtils;
import com.intellij.openapi.actionSystem.AnAction;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.actionSystem.CustomShortcutSet;
import com.intellij.openapi.actionSystem.KeyboardShortcut;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.ui.ValidationInfo;
import com.intellij.ui.NonFocusableCheckBox;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.PlatformIcons;
import org.jetbrains.annotations.NotNull;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import java.awt.Dimension;
import java.awt.Event;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.text.MessageFormat;
import java.util.Collection;

public class AddBuildConfigurationDialog extends DialogWrapper {
  private final JPanel myMainPanel;
  private final JTextField myBCNameTextField;
  private final JLabel myUpDownHint;
  private final JComboBox myTargetPlatformCombo;
  private final NonFocusableCheckBox myPureActionScriptCheckBox;
  private final JComboBox myOutputTypeCombo;
  private final JLabel myTargetDevicesLabel;
  private final JCheckBox myAndroidCheckBox;
  private final JCheckBox myIOSCheckBox;

  private final Collection<String> myUsedNames;

  public AddBuildConfigurationDialog(final Project project,
                                     final String dialogTitle,
                                     final Collection<String> usedNames,
                                     final BuildConfigurationNature defaultNature,
                                     final boolean bcNameEditable) {
    super(project);
    myUsedNames = usedNames;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(6, 5, new Insets(0, 0, 0, 0), -1, -1));
      final JLabel label1 = new JLabel();
      label1.setText("Target platform:");
      label1.setDisplayedMnemonic('P');
      label1.setDisplayedMnemonicIndex(7);
      myMainPanel.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      myTargetPlatformCombo = new JComboBox();
      final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
      defaultComboBoxModel1.addElement("Web");
      myTargetPlatformCombo.setModel(defaultComboBoxModel1);
      myMainPanel.add(myTargetPlatformCombo, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                                 GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                 null, null, null, 0, false));
      myPureActionScriptCheckBox = new NonFocusableCheckBox();
      myPureActionScriptCheckBox.setText("Pure ActionScript");
      myPureActionScriptCheckBox.setMnemonic('U');
      myPureActionScriptCheckBox.setDisplayedMnemonicIndex(1);
      myMainPanel.add(myPureActionScriptCheckBox, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                      GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                      GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                      null, null, null, 0, false));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      final JLabel label2 = new JLabel();
      label2.setText("Configuration name:");
      label2.setDisplayedMnemonic('N');
      label2.setDisplayedMnemonicIndex(14);
      myMainPanel.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      myBCNameTextField = new JTextField();
      myMainPanel.add(myBCNameTextField, new GridConstraints(0, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                             GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                             new Dimension(150, -1), null, 0, false));
      final Spacer spacer2 = new Spacer();
      myMainPanel.add(spacer2, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      final JLabel label3 = new JLabel();
      label3.setText("Output type:");
      label3.setDisplayedMnemonic('O');
      label3.setDisplayedMnemonicIndex(0);
      myMainPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      myOutputTypeCombo = new JComboBox();
      final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
      defaultComboBoxModel2.addElement("Application (*.swf)");
      myOutputTypeCombo.setModel(defaultComboBoxModel2);
      myMainPanel.add(myOutputTypeCombo, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                             GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                             null, null, 0, false));
      myUpDownHint = new JLabel();
      myUpDownHint.setText("");
      myMainPanel.add(myUpDownHint, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                        GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                        null, 0, false));
      myTargetDevicesLabel = new JLabel();
      myTargetDevicesLabel.setText("Target devices:");
      myMainPanel.add(myTargetDevicesLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null,
                                                                null, null, 0, false));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
      myMainPanel.add(panel1, new GridConstraints(4, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                                  null, 0, false));
      myAndroidCheckBox = new JCheckBox();
      myAndroidCheckBox.setText("Android");
      myAndroidCheckBox.setMnemonic('A');
      myAndroidCheckBox.setDisplayedMnemonicIndex(0);
      panel1.add(myAndroidCheckBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer3 = new Spacer();
      panel1.add(spacer3, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                              GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      myIOSCheckBox = new JCheckBox();
      myIOSCheckBox.setText("iOS");
      myIOSCheckBox.setMnemonic('I');
      myIOSCheckBox.setDisplayedMnemonicIndex(0);
      panel1.add(myIOSCheckBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                    GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer4 = new Spacer();
      myMainPanel.add(spacer4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
      label1.setLabelFor(myTargetPlatformCombo);
      label2.setLabelFor(myBCNameTextField);
      label3.setLabelFor(myOutputTypeCombo);
    }
    setTitle(dialogTitle);
    initCombos();
    myTargetPlatformCombo.setSelectedItem(defaultNature.targetPlatform);
    myPureActionScriptCheckBox.setSelected(defaultNature.pureAS);
    myOutputTypeCombo.setSelectedItem(defaultNature.outputType);

    myBCNameTextField.setEditable(bcNameEditable);
    myUpDownHint.setVisible(bcNameEditable);

    if (bcNameEditable) {
      myUpDownHint.setIcon(PlatformIcons.UP_DOWN_ARROWS);
      myUpDownHint.setToolTipText(FlexBundle.message("bc.dialog.up.down.tooltip"));
      final AnAction arrow = new AnAction() {
        @Override
        public void actionPerformed(@NotNull AnActionEvent e) {
          if (e.getInputEvent() instanceof KeyEvent keyEvent) {
            final int code = keyEvent.getKeyCode();
            scrollBy(code == KeyEvent.VK_DOWN ? 1 : code == KeyEvent.VK_UP ? -1 : 0, (keyEvent.getModifiers() & Event.SHIFT_MASK) != 0);
          }
        }
      };
      final KeyboardShortcut up = new KeyboardShortcut(KeyStroke.getKeyStroke(KeyEvent.VK_UP, 0), null);
      final KeyboardShortcut upShift = new KeyboardShortcut(KeyStroke.getKeyStroke(KeyEvent.VK_UP, InputEvent.SHIFT_DOWN_MASK), null);
      final KeyboardShortcut down = new KeyboardShortcut(KeyStroke.getKeyStroke(KeyEvent.VK_DOWN, 0), null);
      final KeyboardShortcut downShift = new KeyboardShortcut(KeyStroke.getKeyStroke(KeyEvent.VK_DOWN, InputEvent.SHIFT_DOWN_MASK), null);
      arrow.registerCustomShortcutSet(new CustomShortcutSet(up, down, upShift, downShift), myBCNameTextField);
    }

    init();
    updateControls();
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  private void updateControls() {
    final boolean mobile = myTargetPlatformCombo.getSelectedItem() == TargetPlatform.Mobile;
    final boolean app = myOutputTypeCombo.getSelectedItem() == OutputType.Application;
    final boolean targetDeviceWasEnabled = myTargetDevicesLabel.isEnabled();

    myTargetDevicesLabel.setEnabled(mobile && app);
    myAndroidCheckBox.setEnabled(mobile && app);
    myIOSCheckBox.setEnabled(mobile && app);

    if (myTargetDevicesLabel.isEnabled() && !targetDeviceWasEnabled) {
      myAndroidCheckBox.setSelected(true);
      myIOSCheckBox.setSelected(true);
    }

    if (!myTargetDevicesLabel.isEnabled()) {
      // disabled but checked for mobile library
      myAndroidCheckBox.setSelected(mobile);
      myIOSCheckBox.setSelected(mobile);
    }
  }

  private void scrollBy(final int delta, boolean shiftPressed) {
    if (delta == 0) return;
    JComboBox combo = shiftPressed ? myOutputTypeCombo : myTargetPlatformCombo;
    final int size = combo.getModel().getSize();
    int next = combo.getSelectedIndex() + delta;
    if (next < 0 || next >= size) {
      if (!UISettings.getInstance().getCycleScrolling()) {
        return;
      }
      next = (next + size) % size;
    }
    combo.setSelectedIndex(next);
  }

  private void initCombos() {
    BCUtils.initTargetPlatformCombo(myTargetPlatformCombo);
    BCUtils.initOutputTypeCombo(myOutputTypeCombo);

    final ActionListener actionListener = new ActionListener() {
      @Override
      public void actionPerformed(final ActionEvent e) {
        updateControls();
      }
    };

    myTargetPlatformCombo.addActionListener(actionListener);
    myOutputTypeCombo.addActionListener(actionListener);
  }

  public void reset(final String bcName, final boolean androidEnabled, final boolean iosEnabled) {
    myBCNameTextField.setText(bcName);
    myAndroidCheckBox.setSelected(androidEnabled);
    myIOSCheckBox.setSelected(iosEnabled);
    updateControls();
  }

  @Override
  public JComponent getPreferredFocusedComponent() {
    return myBCNameTextField.isEditable() ? myBCNameTextField : myTargetPlatformCombo;
  }

  @Override
  protected JComponent createCenterPanel() {
    return myMainPanel;
  }

  @Override
  protected ValidationInfo doValidate() {
    final String name = getBCName();

    if (name.isEmpty()) {
      return new ValidationInfo("Empty name", myBCNameTextField);
    }

    for (final String usedName : myUsedNames) {
      if (name.equals(usedName)) {
        return new ValidationInfo(MessageFormat.format("Name ''{0}'' is already used", name), myBCNameTextField);
      }
    }

    return null;
  }

  public String getBCName() {
    return myBCNameTextField.getText().trim();
  }

  public BuildConfigurationNature getNature() {
    TargetPlatform targetPlatform = (TargetPlatform)myTargetPlatformCombo.getSelectedItem();
    boolean isPureAs = myPureActionScriptCheckBox.isSelected();
    OutputType outputType = (OutputType)myOutputTypeCombo.getSelectedItem();
    return new BuildConfigurationNature(targetPlatform, isPureAs, outputType);
  }

  public boolean isAndroidEnabled() {
    return myAndroidCheckBox.isSelected();
  }

  public boolean isIOSEnabled() {
    return myIOSCheckBox.isSelected();
  }
}

