// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.lang.javascript.flex.projectStructure.ui;

import com.intellij.lang.javascript.flex.FlexUtils;
import com.intellij.lang.javascript.flex.projectStructure.model.AirPackagingOptions;
import com.intellij.lang.javascript.flex.projectStructure.model.ModifiableAirPackagingOptions;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.openapi.util.ActionCallback;
import com.intellij.openapi.util.io.FileUtil;
import com.intellij.openapi.wm.IdeFocusManager;
import com.intellij.ui.IdeBorderFactory;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.border.TitledBorder;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AirDescriptorForm {
  private final JPanel myMainPanel; // required for form reuse
  private final JRadioButton myGeneratedDescriptorRadioButton;
  private final JRadioButton myCustomDescriptorRadioButton;
  private final TextFieldWithBrowseButton myCustomDescriptorTextWithBrowse;
  private final JButton myCreateDescriptorButton;

  public AirDescriptorForm(final Project project, final Runnable descriptorCreator) {
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
      myMainPanel.putClientProperty("BorderFactoryClass", "com.intellij.ui.IdeBorderFactory$PlainSmallWithIndent");
      myMainPanel.setBorder(
        IdeBorderFactory.PlainSmallWithIndent.createTitledBorder(BorderFactory.createEtchedBorder(), "Application descriptor",
                                                                 TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null,
                                                                 null));
      myCustomDescriptorRadioButton = new JRadioButton();
      myCustomDescriptorRadioButton.setText("Custom template:");
      myCustomDescriptorRadioButton.setMnemonic('C');
      myCustomDescriptorRadioButton.setDisplayedMnemonicIndex(0);
      myMainPanel.add(myCustomDescriptorRadioButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                         GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                         GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                         GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myCustomDescriptorTextWithBrowse = new TextFieldWithBrowseButton();
      myMainPanel.add(myCustomDescriptorTextWithBrowse,
                      new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                          GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                          false));
      myGeneratedDescriptorRadioButton = new JRadioButton();
      myGeneratedDescriptorRadioButton.setText("Generated");
      myGeneratedDescriptorRadioButton.setMnemonic('G');
      myGeneratedDescriptorRadioButton.setDisplayedMnemonicIndex(0);
      myMainPanel.add(myGeneratedDescriptorRadioButton,
                      new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myCreateDescriptorButton = new JButton();
      myCreateDescriptorButton.setText("Create...");
      myCreateDescriptorButton.setMnemonic('R');
      myCreateDescriptorButton.setDisplayedMnemonicIndex(1);
      myMainPanel.add(myCreateDescriptorButton,
                      new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      ButtonGroup buttonGroup;
      buttonGroup = new ButtonGroup();
      buttonGroup.add(myCustomDescriptorRadioButton);
      buttonGroup.add(myGeneratedDescriptorRadioButton);
    }
    final ActionListener listener = new ActionListener() {
      @Override
      public void actionPerformed(final ActionEvent e) {
        updateControls();
        if (myCustomDescriptorRadioButton.isSelected()) {
          IdeFocusManager.getInstance(project).requestFocus(myCustomDescriptorTextWithBrowse.getTextField(), true);
        }
      }
    };

    myGeneratedDescriptorRadioButton.addActionListener(listener);
    myCustomDescriptorRadioButton.addActionListener(listener);

    myCustomDescriptorTextWithBrowse.addBrowseFolderListener(project, FlexUtils.createFileChooserDescriptor("xml"));

    myCreateDescriptorButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(final ActionEvent e) {
        descriptorCreator.run();
      }
    });
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  void updateControls() {
    myCustomDescriptorTextWithBrowse.setEnabled(myCustomDescriptorRadioButton.isEnabled() && myCustomDescriptorRadioButton.isSelected());
    myCreateDescriptorButton.setEnabled(myCustomDescriptorRadioButton.isEnabled() && myCustomDescriptorRadioButton.isSelected());
  }

  public void resetFrom(final AirPackagingOptions packagingOptions) {
    myGeneratedDescriptorRadioButton.setSelected(packagingOptions.isUseGeneratedDescriptor());
    myCustomDescriptorRadioButton.setSelected(!packagingOptions.isUseGeneratedDescriptor());
    myCustomDescriptorTextWithBrowse.setText(FileUtil.toSystemDependentName(packagingOptions.getCustomDescriptorPath()));
  }

  public boolean isModified(final ModifiableAirPackagingOptions packagingOptions) {
    if (packagingOptions.isUseGeneratedDescriptor() != myGeneratedDescriptorRadioButton.isSelected()) return true;
    if (!packagingOptions.getCustomDescriptorPath().equals(
      FileUtil.toSystemIndependentName(myCustomDescriptorTextWithBrowse.getText().trim()))) {
      return true;
    }

    return false;
  }

  public void applyTo(final ModifiableAirPackagingOptions model) {
    model.setUseGeneratedDescriptor(myGeneratedDescriptorRadioButton.isSelected());
    model.setCustomDescriptorPath(FileUtil.toSystemIndependentName(myCustomDescriptorTextWithBrowse.getText().trim()));
  }

  public void setUseCustomDescriptor(final String descriptorPath) {
    myCustomDescriptorRadioButton.setSelected(true);
    myCustomDescriptorTextWithBrowse.setText(FileUtil.toSystemDependentName(descriptorPath));
    updateControls();
  }

  public ActionCallback navigateTo(final AirPackagingConfigurableBase.Location location) {
    if (location == AirPackagingConfigurableBase.Location.CustomDescriptor) {
      return IdeFocusManager.findInstance().requestFocus(myCustomDescriptorTextWithBrowse.getChildComponent(), true);
    }
    return ActionCallback.DONE;
  }
}
