package com.intellij.lang.javascript.flex.projectStructure.ui;

import com.intellij.openapi.project.Project;
import com.intellij.openapi.projectRoots.ui.SdkEditor;
import com.intellij.openapi.ui.DialogWrapper;

import javax.swing.JComponent;
import javax.swing.JPanel;
import java.awt.BorderLayout;

public class FlexSdkEditorDialog extends DialogWrapper {
  private final JPanel myContentPane;
  private final SdkEditor mySdkEditor;

  protected FlexSdkEditorDialog(Project project, String sdkPath) {
    super(project);
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myContentPane = new JPanel();
      myContentPane.setLayout(new BorderLayout(0, 0));
    }
    mySdkEditor = null;//new SdkEditor();
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myContentPane; }

  @Override
  protected JComponent createCenterPanel() {
    return myContentPane;
  }
}
