// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.lang.javascript.flex.projectStructure.ui;

import com.intellij.lang.javascript.flex.FlexUtils;
import com.intellij.lang.javascript.flex.projectStructure.model.AirSigningOptions;
import com.intellij.openapi.fileChooser.FileChooserDescriptorFactory;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.openapi.util.ActionCallback;
import com.intellij.openapi.util.io.FileUtil;
import com.intellij.openapi.wm.IdeFocusManager;
import com.intellij.ui.HoverHyperlinkLabel;
import com.intellij.ui.RawCommandLineEditor;
import com.intellij.ui.components.JBRadioButton;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ui.PlatformColors;
import com.intellij.util.ui.UIUtil;
import org.jetbrains.annotations.NotNull;

import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SigningOptionsForm {
  private static final String MORE_OPTIONS = "More options";
  private static final String LESS_OPTIONS = "Less options";

  private final Mode myMode;

  private final JPanel myMainPanel;

  private final JLabel myTargetArchitectureLabel;
  private final JBRadioButton myArchArmv7RadioButton;
  private final JBRadioButton myArchX86RadioButton;
  private final JBRadioButton myArchArmv8RadioButton;

  private final JCheckBox myUseTempCertificateCheckBox;

  private final JLabel myProvisioningProfileLabel;
  private final TextFieldWithBrowseButton myProvisioningProfileTextWithBrowse;
  private final JLabel myKeystoreFileLabel;
  private final TextFieldWithBrowseButton myKeystoreFileTextWithBrowse;
  private final JLabel myIosSdkLabel;
  private final TextFieldWithBrowseButton myIosSdkTextWithBrowse;

  private final HoverHyperlinkLabel myMoreOptionsHyperlinkLabel;

  private final JLabel myKeystoreTypeLabel;
  private final JTextField myKeystoreTypeTextField;
  private final JLabel myKeyAliasLabel;
  private final JTextField myKeyAliasTextField;
  private final JLabel myProviderClassNameLabel;
  private final JTextField myProviderClassNameTextField;
  private final JLabel myTsaUrlLabel;
  private final JTextField myTsaUrlTextField;

  private final JLabel myAdtOptionsLabel;
  private final RawCommandLineEditor myAdtOptionsComponent;

  enum Mode {Desktop, Android, iOS}

  public SigningOptionsForm(final Project project, final Mode mode) {
    myMode = mode;
    {
      myMoreOptionsHyperlinkLabel = new HoverHyperlinkLabel(MORE_OPTIONS);
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(9, 4, new Insets(0, 0, 0, 0), -1, -1));
      myMainPanel.putClientProperty("BorderFactoryClass", "com.intellij.ui.IdeBorderFactory$PlainSmallWithoutIndent");
      myUseTempCertificateCheckBox = new JCheckBox();
      myUseTempCertificateCheckBox.setMargin(new Insets(2, 0, 2, 3));
      myUseTempCertificateCheckBox.setText("Use temporary self-signed certificate");
      myUseTempCertificateCheckBox.setMnemonic('S');
      myUseTempCertificateCheckBox.setDisplayedMnemonicIndex(14);
      myMainPanel.add(myUseTempCertificateCheckBox, new GridConstraints(1, 0, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                        GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                        GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myKeystoreFileLabel = new JLabel();
      myKeystoreFileLabel.setText("Keystore file:");
      myKeystoreFileLabel.setDisplayedMnemonic('F');
      myKeystoreFileLabel.setDisplayedMnemonicIndex(9);
      myMainPanel.add(myKeystoreFileLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                               GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null,
                                                               null, null, 0, false));
      myMoreOptionsHyperlinkLabel.setText("More options");
      myMainPanel.add(myMoreOptionsHyperlinkLabel, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                       GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                                                                       null, null, null, 0, false));
      myProvisioningProfileLabel = new JLabel();
      myProvisioningProfileLabel.setText("Provisioning profile:");
      myProvisioningProfileLabel.setDisplayedMnemonic('V');
      myProvisioningProfileLabel.setDisplayedMnemonicIndex(3);
      myMainPanel.add(myProvisioningProfileLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                      GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                                                                      null, null, null, 0, false));
      myProvisioningProfileTextWithBrowse = new TextFieldWithBrowseButton();
      myMainPanel.add(myProvisioningProfileTextWithBrowse,
                      new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                          GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                          false));
      myProviderClassNameLabel = new JLabel();
      myProviderClassNameLabel.setText("Provider class:");
      myProviderClassNameLabel.setDisplayedMnemonic('R');
      myProviderClassNameLabel.setDisplayedMnemonicIndex(1);
      myMainPanel.add(myProviderClassNameLabel, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                    GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                                                                    null, null, null, 0, false));
      myProviderClassNameTextField = new JTextField();
      myMainPanel.add(myProviderClassNameTextField,
                      new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                          GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                          new Dimension(100, -1), null, 0, false));
      myKeystoreTypeLabel = new JLabel();
      myKeystoreTypeLabel.setText("Keystore type:");
      myKeystoreTypeLabel.setDisplayedMnemonic('T');
      myKeystoreTypeLabel.setDisplayedMnemonicIndex(9);
      myMainPanel.add(myKeystoreTypeLabel, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                               GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null,
                                                               null, null, 0, false));
      myKeystoreFileTextWithBrowse = new TextFieldWithBrowseButton();
      myMainPanel.add(myKeystoreFileTextWithBrowse,
                      new GridConstraints(3, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                          GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                          false));
      myKeyAliasTextField = new JTextField();
      myMainPanel.add(myKeyAliasTextField, new GridConstraints(6, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                               GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                               new Dimension(100, -1), null, 0, false));
      myKeyAliasLabel = new JLabel();
      myKeyAliasLabel.setText("Key alias:");
      myKeyAliasLabel.setDisplayedMnemonic('I');
      myKeyAliasLabel.setDisplayedMnemonicIndex(6);
      myMainPanel.add(myKeyAliasLabel, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                           GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                           null, 0, false));
      myKeystoreTypeTextField = new JTextField();
      myMainPanel.add(myKeystoreTypeTextField, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                                   GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                   null, new Dimension(100, -1), null, 0, false));
      myTsaUrlTextField = new JTextField();
      myMainPanel.add(myTsaUrlTextField, new GridConstraints(7, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                             GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                             new Dimension(100, -1), null, 0, false));
      myTsaUrlLabel = new JLabel();
      myTsaUrlLabel.setText("TSA:");
      myMainPanel.add(myTsaUrlLabel, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                         GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                         null, 0, false));
      myIosSdkLabel = new JLabel();
      myIosSdkLabel.setText("Apple iOS SDK:");
      myIosSdkLabel.setDisplayedMnemonic('O');
      myIosSdkLabel.setDisplayedMnemonicIndex(7);
      myMainPanel.add(myIosSdkLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                         GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                         null, 0, false));
      myIosSdkTextWithBrowse = new TextFieldWithBrowseButton();
      myMainPanel.add(myIosSdkTextWithBrowse,
                      new GridConstraints(4, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                          GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                          false));
      myAdtOptionsLabel = new JLabel();
      myAdtOptionsLabel.setText("Additional ADT options:");
      myAdtOptionsLabel.setDisplayedMnemonic('D');
      myAdtOptionsLabel.setDisplayedMnemonicIndex(1);
      myMainPanel.add(myAdtOptionsLabel, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                             GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                             null, 0, false));
      myAdtOptionsComponent = new RawCommandLineEditor();
      myMainPanel.add(myAdtOptionsComponent, new GridConstraints(8, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                                 GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                 GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                 null, null, null, 0, false));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(1, 5, new Insets(0, 0, 0, 0), -1, -1));
      myMainPanel.add(panel1, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                                  null, 0, false));
      myTargetArchitectureLabel = new JLabel();
      myTargetArchitectureLabel.setText("Architecture:");
      panel1.add(myTargetArchitectureLabel,
                 new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myArchArmv7RadioButton = new JBRadioButton();
      myArchArmv7RadioButton.setText("armv7");
      panel1.add(myArchArmv7RadioButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
                                                             GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                             GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myArchX86RadioButton = new JBRadioButton();
      myArchX86RadioButton.setText("x86");
      myArchX86RadioButton.setMnemonic('X');
      myArchX86RadioButton.setDisplayedMnemonicIndex(0);
      panel1.add(myArchX86RadioButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
                                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                           GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer1 = new Spacer();
      panel1.add(spacer1, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                              GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      myArchArmv8RadioButton = new JBRadioButton();
      myArchArmv8RadioButton.setText("armv8");
      myArchArmv8RadioButton.setMnemonic('M');
      myArchArmv8RadioButton.setDisplayedMnemonicIndex(2);
      panel1.add(myArchArmv8RadioButton, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
                                                             GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                             GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myKeystoreFileLabel.setLabelFor(myKeystoreFileTextWithBrowse);
      myProvisioningProfileLabel.setLabelFor(myProvisioningProfileTextWithBrowse);
      myProviderClassNameLabel.setLabelFor(myProviderClassNameTextField);
      myKeystoreTypeLabel.setLabelFor(myKeystoreTypeTextField);
      myKeyAliasLabel.setLabelFor(myKeyAliasTextField);
      myTsaUrlLabel.setLabelFor(myTsaUrlTextField);
      myIosSdkLabel.setLabelFor(myIosSdkTextWithBrowse);
      myAdtOptionsLabel.setLabelFor(myAdtOptionsComponent);
      ButtonGroup buttonGroup;
      buttonGroup = new ButtonGroup();
      buttonGroup.add(myArchArmv7RadioButton);
      buttonGroup.add(myArchX86RadioButton);
      buttonGroup.add(myArchArmv8RadioButton);
    }
    myUseTempCertificateCheckBox.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(final ActionEvent e) {
        updateControls();
      }
    });

    myProvisioningProfileTextWithBrowse.addBrowseFolderListener(project, FlexUtils.createFileChooserDescriptor("mobileprovision"));

    myIosSdkTextWithBrowse.addBrowseFolderListener(project, FileChooserDescriptorFactory.createSingleFolderDescriptor());

    var d =
      mode == Mode.iOS ? FlexUtils.createFileChooserDescriptor("p12") : FileChooserDescriptorFactory.createSingleFileNoJarsDescriptor();
    myKeystoreFileTextWithBrowse.addBrowseFolderListener(project, d);

    myAdtOptionsComponent.setDialogCaption("Additional ADT Options");

    myMoreOptionsHyperlinkLabel.setText(MORE_OPTIONS);
    myMoreOptionsHyperlinkLabel.addHyperlinkListener(new HyperlinkListener() {
      @Override
      public void hyperlinkUpdate(HyperlinkEvent e) {
        if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
          showMoreOptions(!isShowingMoreOptions());
        }
      }
    });

    updateMoreOptions();

    switch (mode) {
      case Desktop:
        myTargetArchitectureLabel.setVisible(false);
        myArchArmv7RadioButton.setVisible(false);
        myArchX86RadioButton.setVisible(false);
        myArchArmv8RadioButton.setVisible(false);
        // no break here
      case Android:
        myProvisioningProfileLabel.setVisible(false);
        myProvisioningProfileTextWithBrowse.setVisible(false);
        myIosSdkLabel.setVisible(false);
        myIosSdkTextWithBrowse.setVisible(false);
        myAdtOptionsLabel.setVisible(false);
        myAdtOptionsComponent.setVisible(false);
        break;
      case iOS:
        myTargetArchitectureLabel.setVisible(false);
        myArchArmv7RadioButton.setVisible(false);
        myArchX86RadioButton.setVisible(false);
        myArchArmv8RadioButton.setVisible(false);
        myUseTempCertificateCheckBox.setVisible(false);
        showMoreOptions(false);
        myMoreOptionsHyperlinkLabel.setVisible(false);
        break;
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  private void showMoreOptions(final boolean show) {
    myMoreOptionsHyperlinkLabel.setText(show ? LESS_OPTIONS : MORE_OPTIONS);
    updateMoreOptions();
  }

  private boolean isShowingMoreOptions() {
    return myMoreOptionsHyperlinkLabel.getText().contains(LESS_OPTIONS);
  }

  private void updateMoreOptions() {
    final boolean showingMoreOption = isShowingMoreOptions();

    myKeystoreTypeLabel.setVisible(showingMoreOption);
    myKeystoreTypeTextField.setVisible(showingMoreOption);
    myKeyAliasLabel.setVisible(showingMoreOption);
    myKeyAliasTextField.setVisible(showingMoreOption);
    myProviderClassNameLabel.setVisible(showingMoreOption);
    myProviderClassNameTextField.setVisible(showingMoreOption);
    myTsaUrlLabel.setVisible(showingMoreOption && myMode != Mode.Android);
    myTsaUrlTextField.setVisible(showingMoreOption && myMode != Mode.Android);
  }

  private void updateControls() {
    final boolean enabled = !myUseTempCertificateCheckBox.isVisible() || !myUseTempCertificateCheckBox.isSelected();

    myProvisioningProfileLabel.setEnabled(enabled);
    myProviderClassNameTextField.setEnabled(enabled);
    myKeystoreFileLabel.setEnabled(enabled);
    myKeystoreFileTextWithBrowse.setEnabled(enabled);
    myIosSdkLabel.setEnabled(enabled);
    myIosSdkTextWithBrowse.setEnabled(enabled);

    myMoreOptionsHyperlinkLabel.setEnabled(enabled);
    if (myMoreOptionsHyperlinkLabel.isEnabled()) {
      myMoreOptionsHyperlinkLabel.setForeground(PlatformColors.BLUE); // workaround of JLabel-related workaround at UIUtil.setEnabled(..)
    }

    myKeystoreTypeLabel.setEnabled(enabled);
    myKeystoreTypeTextField.setEnabled(enabled);
    myKeyAliasLabel.setEnabled(enabled);
    myKeyAliasTextField.setEnabled(enabled);
    myProviderClassNameLabel.setEnabled(enabled);
    myProviderClassNameTextField.setEnabled(enabled);
    myTsaUrlLabel.setEnabled(enabled);
    myTsaUrlTextField.setEnabled(enabled);
  }

  public void setEnabled(final boolean enabled) {
    UIUtil.setEnabled(myMainPanel, enabled, true);
    if (enabled) {
      updateControls();
    }
  }

  private @NotNull String getArch() {
    if (myArchX86RadioButton.isSelected()) return AirSigningOptions.ARCH_X86;
    if (myArchArmv8RadioButton.isSelected()) return AirSigningOptions.ARCH_ARMV8;
    return AirSigningOptions.ARCH_ARMV7;
  }

  public void resetFrom(final AirSigningOptions signingOptions) {
    if (signingOptions.getArch().equals(AirSigningOptions.ARCH_X86)) {
      myArchX86RadioButton.setSelected(true);
    }
    else if (signingOptions.getArch().equals(AirSigningOptions.ARCH_ARMV8)) {
      myArchArmv8RadioButton.setSelected(true);
    }
    else {
      myArchArmv7RadioButton.setSelected(true);
    }
    myUseTempCertificateCheckBox.setSelected(signingOptions.isUseTempCertificate());
    myProvisioningProfileTextWithBrowse.setText(FileUtil.toSystemDependentName(signingOptions.getProvisioningProfilePath()));
    myKeystoreFileTextWithBrowse.setText(FileUtil.toSystemDependentName(signingOptions.getKeystorePath()));
    myIosSdkTextWithBrowse.setText(FileUtil.toSystemDependentName(signingOptions.getIOSSdkPath()));
    myAdtOptionsComponent.setText(signingOptions.getADTOptions());
    myKeystoreTypeTextField.setText(signingOptions.getKeystoreType());
    myKeyAliasTextField.setText(signingOptions.getKeyAlias());
    myProviderClassNameTextField.setText(signingOptions.getProvider());
    myTsaUrlTextField.setText(signingOptions.getTsa());
  }

  public boolean isModified(final AirSigningOptions signingOptions) {
    if (myTargetArchitectureLabel.isVisible() && !getArch().equals(signingOptions.getArch())) return true;

    if (myUseTempCertificateCheckBox.isVisible() && myUseTempCertificateCheckBox.isSelected() != signingOptions.isUseTempCertificate()) {
      return true;
    }

    final String profilePath = FileUtil.toSystemIndependentName(myProvisioningProfileTextWithBrowse.getText().trim());
    if (myProvisioningProfileTextWithBrowse.isVisible() && !profilePath.equals(signingOptions.getProvisioningProfilePath())) return true;

    final String keystorePath = FileUtil.toSystemIndependentName(myKeystoreFileTextWithBrowse.getText().trim());
    if (!keystorePath.equals(signingOptions.getKeystorePath())) return true;

    final String iosSdkPath = FileUtil.toSystemIndependentName(myIosSdkTextWithBrowse.getText().trim());
    if (myIosSdkTextWithBrowse.isVisible() && !iosSdkPath.equals(signingOptions.getIOSSdkPath())) return true;

    if (myAdtOptionsComponent.isVisible() && !myAdtOptionsComponent.getText().equals(signingOptions.getADTOptions())) return false;
    if (!myKeystoreTypeTextField.getText().trim().equals(signingOptions.getKeystoreType())) return true;
    if (!myKeyAliasTextField.getText().equals(signingOptions.getKeyAlias())) return true;
    if (!myProviderClassNameTextField.getText().equals(signingOptions.getProvider())) return true;
    if (!myTsaUrlTextField.getText().equals(signingOptions.getTsa())) return true;

    return false;
  }

  public void applyTo(final AirSigningOptions signingOptions) {
    signingOptions.setArch(getArch());
    signingOptions.setUseTempCertificate(myUseTempCertificateCheckBox.isSelected());
    signingOptions.setProvisioningProfilePath(FileUtil.toSystemIndependentName(myProvisioningProfileTextWithBrowse.getText().trim()));
    signingOptions.setKeystorePath(FileUtil.toSystemIndependentName(myKeystoreFileTextWithBrowse.getText().trim()));
    signingOptions.setIOSSdkPath(FileUtil.toSystemIndependentName(myIosSdkTextWithBrowse.getText().trim()));
    signingOptions.setADTOptions(myAdtOptionsComponent.getText().trim());
    signingOptions.setKeystoreType(myKeystoreTypeTextField.getText().trim());
    signingOptions.setKeyAlias(myKeyAliasTextField.getText());
    signingOptions.setProvider(myProviderClassNameTextField.getText());
    signingOptions.setTsa(myTsaUrlTextField.getText());
  }

  public ActionCallback navigateTo(final AirPackagingConfigurableBase.Location location) {
    return switch (location) {
      case ProvisioningProfile ->
        IdeFocusManager.findInstance().requestFocus(myProvisioningProfileTextWithBrowse.getChildComponent(), true);
      case Keystore -> IdeFocusManager.findInstance().requestFocus(myKeystoreFileTextWithBrowse.getChildComponent(), true);
      case IosSdkPath -> IdeFocusManager.findInstance().requestFocus(myIosSdkTextWithBrowse.getTextField(), true);
      default -> ActionCallback.DONE;
    };
  }
}
