// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.lang.javascript.flex.run;

import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.options.SettingsEditor;
import com.intellij.openapi.project.Project;
import com.intellij.ui.IdeBorderFactory;
import com.intellij.ui.components.JBLabel;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ui.UIUtil;
import org.jetbrains.annotations.NotNull;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import static com.intellij.lang.javascript.flex.run.FlashRunnerParameters.AirMobileDebugTransport;
import static com.intellij.lang.javascript.flex.run.RemoteFlashRunnerParameters.RemoteDebugTarget;

public class RemoteFlashRunConfigurationForm extends SettingsEditor<RemoteFlashRunConfiguration> {

  private final JPanel myMainPanel;
  private final BCCombo myBCCombo;

  private final JRadioButton myOnComputerRadioButton;
  private final JRadioButton myOnAndroidDeviceRadioButton;
  private final JRadioButton myOnIOSDeviceRadioButton;

  private final JPanel myDeviceOptionsPanel;
  private final JRadioButton myDebugOverNetworkRadioButton;
  private final JRadioButton myDebugOverUSBRadioButton;
  private final JTextField myUsbDebugPortTextField;

  private final Project myProject;

  public RemoteFlashRunConfigurationForm(final Project project) {
    myProject = project;
    {
      myBCCombo = new BCCombo(myProject);
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(5, 3, new Insets(0, 0, 0, 0), -1, -1));
      final JLabel label1 = new JLabel();
      label1.setText("Build configuration:");
      label1.setDisplayedMnemonic('C');
      label1.setDisplayedMnemonicIndex(6);
      myMainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      final Spacer spacer2 = new Spacer();
      myMainPanel.add(spacer2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      final JBLabel jBLabel1 = new JBLabel();
      jBLabel1.setComponentStyle(UIUtil.ComponentStyle.MINI);
      jBLabel1.setFontColor(UIUtil.FontColor.BRIGHTER);
      jBLabel1.setText("Debugger is taken from the Flex/AIR SDK configured for the selected build configuration.");
      myMainPanel.add(jBLabel1, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                    GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 2,
                                                    false));
      final JBLabel jBLabel2 = new JBLabel();
      jBLabel2.setComponentStyle(UIUtil.ComponentStyle.MINI);
      jBLabel2.setFontColor(UIUtil.FontColor.BRIGHTER);
      jBLabel2.setText("Source files are searched according to the dependencies of the selected build configuration.");
      myMainPanel.add(jBLabel2, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                    GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 2,
                                                    false));
      myMainPanel.add(myBCCombo, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
                                                     GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                     GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                     null, null, 0, false));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
      panel1.putClientProperty("BorderFactoryClass", "com.intellij.ui.IdeBorderFactory$PlainSmallWithIndent");
      myMainPanel.add(panel1, new GridConstraints(3, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                                  null, 0, false));
      panel1.setBorder(IdeBorderFactory.PlainSmallWithIndent.createTitledBorder(BorderFactory.createEtchedBorder(), "Debugged app runs on:",
                                                                                TitledBorder.DEFAULT_JUSTIFICATION,
                                                                                TitledBorder.DEFAULT_POSITION, null, null));
      myOnAndroidDeviceRadioButton = new JRadioButton();
      myOnAndroidDeviceRadioButton.setEnabled(true);
      myOnAndroidDeviceRadioButton.setText("Android device");
      myOnAndroidDeviceRadioButton.setMnemonic('V');
      myOnAndroidDeviceRadioButton.setDisplayedMnemonicIndex(10);
      panel1.add(myOnAndroidDeviceRadioButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                   GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                   null, null, null, 0, false));
      myOnComputerRadioButton = new JRadioButton();
      myOnComputerRadioButton.setText("This or remote computer");
      myOnComputerRadioButton.setMnemonic('T');
      myOnComputerRadioButton.setDisplayedMnemonicIndex(0);
      panel1.add(myOnComputerRadioButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                              GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                              GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myDeviceOptionsPanel = new JPanel();
      myDeviceOptionsPanel.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
      panel1.add(myDeviceOptionsPanel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                           null, null, null, 0, false));
      myDebugOverNetworkRadioButton = new JRadioButton();
      myDebugOverNetworkRadioButton.setText("Network");
      myDebugOverNetworkRadioButton.setMnemonic('W');
      myDebugOverNetworkRadioButton.setDisplayedMnemonicIndex(3);
      myDeviceOptionsPanel.add(myDebugOverNetworkRadioButton,
                               new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                   GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myDebugOverUSBRadioButton = new JRadioButton();
      myDebugOverUSBRadioButton.setText("USB, port:");
      myDebugOverUSBRadioButton.setMnemonic('B');
      myDebugOverUSBRadioButton.setDisplayedMnemonicIndex(2);
      myDeviceOptionsPanel.add(myDebugOverUSBRadioButton,
                               new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                   GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myUsbDebugPortTextField = new JTextField();
      myUsbDebugPortTextField.setColumns(4);
      myDeviceOptionsPanel.add(myUsbDebugPortTextField,
                               new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null,
                                                   0, false));
      final JLabel label2 = new JLabel();
      label2.setText("Debug on device over: ");
      myDeviceOptionsPanel.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                           GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                           null, 0, false));
      myOnIOSDeviceRadioButton = new JRadioButton();
      myOnIOSDeviceRadioButton.setText("iOS device");
      myOnIOSDeviceRadioButton.setMnemonic('S');
      myOnIOSDeviceRadioButton.setDisplayedMnemonicIndex(2);
      panel1.add(myOnIOSDeviceRadioButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                               GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer3 = new Spacer();
      panel1.add(spacer3, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                              GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      label1.setLabelFor(myBCCombo);
      ButtonGroup buttonGroup;
      buttonGroup = new ButtonGroup();
      buttonGroup.add(myOnAndroidDeviceRadioButton);
      buttonGroup.add(myOnComputerRadioButton);
      buttonGroup.add(myOnIOSDeviceRadioButton);
      buttonGroup = new ButtonGroup();
      buttonGroup.add(myDebugOverNetworkRadioButton);
      buttonGroup.add(myDebugOverUSBRadioButton);
    }

    final ActionListener listener = new ActionListener() {
      @Override
      public void actionPerformed(final ActionEvent e) {
        updateControls();
      }
    };

    myOnComputerRadioButton.addActionListener(listener);
    myOnAndroidDeviceRadioButton.addActionListener(listener);
    myOnIOSDeviceRadioButton.addActionListener(listener);
    myDebugOverNetworkRadioButton.addActionListener(listener);
    myDebugOverUSBRadioButton.addActionListener(listener);
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  @Override
  protected @NotNull JComponent createEditor() {
    return myMainPanel;
  }

  @Override
  protected void resetEditorFrom(final @NotNull RemoteFlashRunConfiguration configuration) {
    final RemoteFlashRunnerParameters params = configuration.getRunnerParameters();
    myBCCombo.resetFrom(params);

    myOnComputerRadioButton.setSelected(params.getRemoteDebugTarget() == RemoteDebugTarget.Computer);
    myOnAndroidDeviceRadioButton.setSelected(params.getRemoteDebugTarget() == RemoteDebugTarget.AndroidDevice);
    myOnIOSDeviceRadioButton.setSelected(params.getRemoteDebugTarget() == RemoteDebugTarget.iOSDevice);

    myDebugOverNetworkRadioButton.setSelected(params.getDebugTransport() == AirMobileDebugTransport.Network);
    myDebugOverUSBRadioButton.setSelected(params.getDebugTransport() == AirMobileDebugTransport.USB);
    myUsbDebugPortTextField.setText(String.valueOf(params.getUsbDebugPort()));

    updateControls();
  }

  @Override
  protected void applyEditorTo(final @NotNull RemoteFlashRunConfiguration configuration) throws ConfigurationException {
    final RemoteFlashRunnerParameters params = configuration.getRunnerParameters();
    myBCCombo.applyTo(params);

    final RemoteDebugTarget remoteDebugTarget = myOnComputerRadioButton.isSelected()
                                                ? RemoteDebugTarget.Computer
                                                : myOnAndroidDeviceRadioButton.isSelected()
                                                  ? RemoteDebugTarget.AndroidDevice
                                                  : RemoteDebugTarget.iOSDevice;
    params.setRemoteDebugTarget(remoteDebugTarget);

    params.setDebugTransport(myDebugOverNetworkRadioButton.isSelected()
                             ? AirMobileDebugTransport.Network
                             : AirMobileDebugTransport.USB);
    try {
      final int port = Integer.parseInt(myUsbDebugPortTextField.getText().trim());
      if (port > 0 && port < 65535) {
        params.setUsbDebugPort(port);
      }
    }
    catch (NumberFormatException ignore) {/*ignore*/}
  }

  @Override
  protected void disposeEditor() {
    myBCCombo.dispose();
  }

  private void updateControls() {
    UIUtil.setEnabled(myDeviceOptionsPanel, myOnAndroidDeviceRadioButton.isSelected() || myOnIOSDeviceRadioButton.isSelected(), true);
    myUsbDebugPortTextField.setEnabled(myDebugOverUSBRadioButton.isEnabled() && myDebugOverUSBRadioButton.isSelected());
  }
}
