// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.jetbrains.lang.dart.ide.errorTreeView;

import com.intellij.ui.HoverHyperlinkLabel;
import com.intellij.ui.HyperlinkAdapter;
import com.intellij.ui.TitledSeparator;
import com.intellij.ui.components.JBCheckBox;
import com.intellij.ui.components.JBRadioButton;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jetbrains.lang.dart.DartBundle;
import org.jetbrains.annotations.NotNull;

import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.event.HyperlinkEvent;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

public class DartProblemsFilterForm {

  interface FilterListener {
    void filtersChanged();

    void filtersResetRequested();
  }


  private final JPanel myMainPanel;

  private final JBCheckBox myErrorsCheckBox;
  private final JBCheckBox myWarningsCheckBox;
  private final JBCheckBox myHintsCheckBox;

  private final JBRadioButton myWholeProjectRadioButton;
  private final JBRadioButton myCurrentContentRootRadioButton;
  private final JBRadioButton myCurrentDartPackageRadioButton;
  private final JBRadioButton myCurrentDirectoryRadioButton;
  private final JBRadioButton myCurrentFileRadioButton;

  private final HoverHyperlinkLabel myResetFilterHyperlink;

  public DartProblemsFilterForm() {
    {
      myResetFilterHyperlink = new HoverHyperlinkLabel(DartBundle.message("dart.problems.filter.popup.link.reset.filter"));
      myResetFilterHyperlink.addHyperlinkListener(new HyperlinkAdapter() {
        @Override
        protected void hyperlinkActivated(final @NotNull HyperlinkEvent e) {
          myListeners.forEach(FilterListener::filtersResetRequested);
        }
      });
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(9, 5, new Insets(5, 10, 10, 5), -1, -1));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      this.$$$loadLabelText$$$(myResetFilterHyperlink,
                               this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.problems.filter.popup.link.reset.filter"));
      myMainPanel.add(myResetFilterHyperlink, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                  GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                  GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
      myWholeProjectRadioButton = new JBRadioButton();
      myWholeProjectRadioButton.setMargin(new Insets(0, 2, 0, 2));
      this.$$$loadButtonText$$$(myWholeProjectRadioButton,
                                this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.problems.filter.popup.radio.whole.project"));
      myMainPanel.add(myWholeProjectRadioButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                     GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                                                                     null, null, null, 0, false));
      myCurrentContentRootRadioButton = new JBRadioButton();
      myCurrentContentRootRadioButton.setMargin(new Insets(0, 2, 0, 2));
      this.$$$loadButtonText$$$(myCurrentContentRootRadioButton, this.$$$getMessageFromBundle$$$("messages/DartBundle",
                                                                                                 "dart.problems.filter.popup.radio.current.content.root"));
      myMainPanel.add(myCurrentContentRootRadioButton,
                      new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myCurrentDirectoryRadioButton = new JBRadioButton();
      myCurrentDirectoryRadioButton.setMargin(new Insets(0, 2, 0, 2));
      this.$$$loadButtonText$$$(myCurrentDirectoryRadioButton, this.$$$getMessageFromBundle$$$("messages/DartBundle",
                                                                                               "dart.problems.filter.popup.radio.current.directory"));
      myMainPanel.add(myCurrentDirectoryRadioButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                         GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                                                                         null, null, null, 0, false));
      myCurrentFileRadioButton = new JBRadioButton();
      myCurrentFileRadioButton.setMargin(new Insets(0, 2, 0, 2));
      this.$$$loadButtonText$$$(myCurrentFileRadioButton,
                                this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.problems.filter.popup.radio.current.file"));
      myMainPanel.add(myCurrentFileRadioButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                    GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                                                                    null, null, null, 0, false));
      myErrorsCheckBox = new JBCheckBox();
      this.$$$loadButtonText$$$(myErrorsCheckBox,
                                this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.problems.filter.popup.check.box.errors"));
      myMainPanel.add(myErrorsCheckBox, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                            GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                            null, 0, false));
      myWarningsCheckBox = new JBCheckBox();
      this.$$$loadButtonText$$$(myWarningsCheckBox,
                                this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.problems.filter.popup.check.box.warnings"));
      myMainPanel.add(myWarningsCheckBox, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                              GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null,
                                                              null, null, 0, false));
      final TitledSeparator titledSeparator1 = new TitledSeparator();
      titledSeparator1.setText(this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.problems.filter.popup.title.files"));
      myMainPanel.add(titledSeparator1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final TitledSeparator titledSeparator2 = new TitledSeparator();
      titledSeparator2.setText(this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.problems.filter.popup.title.severity"));
      myMainPanel.add(titledSeparator2, new GridConstraints(0, 2, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer2 = new Spacer();
      myMainPanel.add(spacer2, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 15), new Dimension(-1, 15),
                                                   new Dimension(-1, 15), 0, false));
      final Spacer spacer3 = new Spacer();
      myMainPanel.add(spacer3, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                   GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(15, -1), new Dimension(15, -1),
                                                   new Dimension(15, -1), 0, false));
      final Spacer spacer4 = new Spacer();
      myMainPanel.add(spacer4, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                   GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(30, -1), new Dimension(30, -1),
                                                   new Dimension(30, -1), 0, false));
      final Spacer spacer5 = new Spacer();
      myMainPanel.add(spacer5, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      myCurrentDartPackageRadioButton = new JBRadioButton();
      myCurrentDartPackageRadioButton.setMargin(new Insets(0, 2, 0, 2));
      this.$$$loadButtonText$$$(myCurrentDartPackageRadioButton, this.$$$getMessageFromBundle$$$("messages/DartBundle",
                                                                                                 "dart.problems.filter.popup.radio.current.dart.package"));
      myMainPanel.add(myCurrentDartPackageRadioButton,
                      new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myHintsCheckBox = new JBCheckBox();
      this.$$$loadButtonText$$$(myHintsCheckBox,
                                this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.problems.filter.popup.check.box.hints"));
      myMainPanel.add(myHintsCheckBox, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                           GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                           null, 0, false));
      ButtonGroup buttonGroup;
      buttonGroup = new ButtonGroup();
      buttonGroup.add(myCurrentDirectoryRadioButton);
      buttonGroup.add(myCurrentFileRadioButton);
      buttonGroup.add(myWholeProjectRadioButton);
      buttonGroup.add(myCurrentContentRootRadioButton);
      buttonGroup.add(myCurrentDartPackageRadioButton);
    }
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  private final List<FilterListener> myListeners = new ArrayList<>();

  public void reset(final @NotNull DartProblemsPresentationHelper presentationHelper) {
    myErrorsCheckBox.setSelected(presentationHelper.isShowErrors());
    myWarningsCheckBox.setSelected(presentationHelper.isShowWarnings());
    myHintsCheckBox.setSelected(presentationHelper.isShowHints());

    if (presentationHelper.getFileFilterMode() == DartProblemsViewSettings.FileFilterMode.File) {
      myCurrentFileRadioButton.setSelected(true);
    }
    else if (presentationHelper.getFileFilterMode() == DartProblemsViewSettings.FileFilterMode.Directory) {
      myCurrentDirectoryRadioButton.setSelected(true);
    }
    else if (presentationHelper.getFileFilterMode() == DartProblemsViewSettings.FileFilterMode.DartPackage) {
      myCurrentDartPackageRadioButton.setSelected(true);
    }
    else if (presentationHelper.getFileFilterMode() == DartProblemsViewSettings.FileFilterMode.ContentRoot) {
      myCurrentContentRootRadioButton.setSelected(true);
    }
    else {
      myWholeProjectRadioButton.setSelected(true);
    }
  }

  public void addListener(final @NotNull FilterListener filterListener) {
    myListeners.add(filterListener);

    final ActionListener listener = e -> filterListener.filtersChanged();

    myErrorsCheckBox.addActionListener(listener);
    myWarningsCheckBox.addActionListener(listener);
    myHintsCheckBox.addActionListener(listener);

    myWholeProjectRadioButton.addActionListener(listener);
    myCurrentContentRootRadioButton.addActionListener(listener);
    myCurrentDartPackageRadioButton.addActionListener(listener);
    myCurrentDirectoryRadioButton.addActionListener(listener);
    myCurrentFileRadioButton.addActionListener(listener);
  }

  public JPanel getMainPanel() {
    return myMainPanel;
  }

  public boolean isShowErrors() {
    return myErrorsCheckBox.isSelected();
  }

  public boolean isShowWarnings() {
    return myWarningsCheckBox.isSelected();
  }

  public boolean isShowHints() {
    return myHintsCheckBox.isSelected();
  }

  public @NotNull DartProblemsViewSettings.FileFilterMode getFileFilterMode() {
    if (myCurrentFileRadioButton.isSelected()) return DartProblemsViewSettings.FileFilterMode.File;
    if (myCurrentDirectoryRadioButton.isSelected()) return DartProblemsViewSettings.FileFilterMode.Directory;
    if (myCurrentDartPackageRadioButton.isSelected()) return DartProblemsViewSettings.FileFilterMode.DartPackage;
    if (myCurrentContentRootRadioButton.isSelected()) return DartProblemsViewSettings.FileFilterMode.ContentRoot;
    return DartProblemsViewSettings.FileFilterMode.All;
  }
}
