// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.jetbrains.lang.dart.ide.errorTreeView;

import com.intellij.openapi.project.Project;
import com.intellij.ui.HoverHyperlinkLabel;
import com.intellij.ui.HyperlinkAdapter;
import com.intellij.ui.TitledSeparator;
import com.intellij.ui.components.JBCheckBox;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jetbrains.lang.dart.DartBundle;
import com.jetbrains.lang.dart.sdk.DartConfigurable;
import org.jetbrains.annotations.NotNull;

import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.event.HyperlinkEvent;
import java.awt.Insets;
import java.lang.reflect.Method;
import java.util.ResourceBundle;

public class DartAnalysisServerSettingsForm {

  interface ServerSettingsListener {
    void settingsChanged();
  }

  private final Project myProject;

  private final JPanel myMainPanel;
  private final HoverHyperlinkLabel myDartSettingsHyperlink;
  private final HoverHyperlinkLabel myAnalysisDiagnosticsHyperlink;
  private final JBCheckBox packageScopedAnalysisCheckbox;

  DartAnalysisServerSettingsForm(final @NotNull Project project) {
    myProject = project;
    {
      myDartSettingsHyperlink = new HoverHyperlinkLabel(DartBundle.message("open.dart.plugin.settings"));
      myDartSettingsHyperlink.addHyperlinkListener(new HyperlinkAdapter() {
        @Override
        protected void hyperlinkActivated(final @NotNull HyperlinkEvent e) {
          DartConfigurable.openDartSettings(myProject);
        }
      });
      myAnalysisDiagnosticsHyperlink = new HoverHyperlinkLabel(DartBundle.message("analysis.server.settings.diagnostics"));
      myAnalysisDiagnosticsHyperlink.addHyperlinkListener(new HyperlinkAdapter() {
        @Override
        protected void hyperlinkActivated(final @NotNull HyperlinkEvent e) {
          new AnalysisServerDiagnosticsAction().run(myProject);
        }
      });
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(6, 1, new Insets(5, 10, 10, 5), -1, -1));
      this.$$$loadLabelText$$$(myDartSettingsHyperlink,
                               this.$$$getMessageFromBundle$$$("messages/DartBundle", "open.dart.plugin.settings"));
      myMainPanel.add(myDartSettingsHyperlink, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                   GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                   GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
      this.$$$loadLabelText$$$(myAnalysisDiagnosticsHyperlink,
                               this.$$$getMessageFromBundle$$$("messages/DartBundle", "analysis.server.settings.diagnostics"));
      myMainPanel.add(myAnalysisDiagnosticsHyperlink,
                      new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0,
                                          false));
      packageScopedAnalysisCheckbox = new JBCheckBox();
      this.$$$loadButtonText$$$(packageScopedAnalysisCheckbox,
                                this.$$$getMessageFromBundle$$$("messages/DartBundle", "analysis.server.settings.package.analysis"));
      myMainPanel.add(packageScopedAnalysisCheckbox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                         GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                                                                         null, null, null, 0, false));
      final TitledSeparator titledSeparator1 = new TitledSeparator();
      titledSeparator1.setText("");
      myMainPanel.add(titledSeparator1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final TitledSeparator titledSeparator2 = new TitledSeparator();
      titledSeparator2.setText("");
      myMainPanel.add(titledSeparator2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  public void reset(final @NotNull DartProblemsPresentationHelper presentationHelper) {
    if (presentationHelper.getScopedAnalysisMode() == DartProblemsViewSettings.ScopedAnalysisMode.DartPackage) {
      packageScopedAnalysisCheckbox.setSelected(true);
    }
    else {
      packageScopedAnalysisCheckbox.setSelected(false);
    }
  }

  public void addListener(final @NotNull ServerSettingsListener serverSettingsListener) {
    packageScopedAnalysisCheckbox.addActionListener(e -> serverSettingsListener.settingsChanged());
  }

  public JPanel getMainPanel() {
    return myMainPanel;
  }

  public @NotNull DartProblemsViewSettings.ScopedAnalysisMode getScopeAnalysisMode() {
    if (packageScopedAnalysisCheckbox.isSelected()) {
      return DartProblemsViewSettings.ScopedAnalysisMode.DartPackage;
    }
    return DartProblemsViewSettings.ScopedAnalysisMode.All;
  }
}
