// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.lang.javascript.flex.flexunit;

import com.intellij.execution.ExecutionBundle;
import com.intellij.execution.configuration.BrowseModuleValueActionListener;
import com.intellij.execution.configurations.RuntimeConfigurationError;
import com.intellij.javascript.flex.resolve.ActionScriptClassResolver;
import com.intellij.lang.javascript.flex.FlexBundle;
import com.intellij.lang.javascript.flex.FlexMethodChooserDialog;
import com.intellij.lang.javascript.flex.projectStructure.model.FlexBuildConfiguration;
import com.intellij.lang.javascript.psi.JSFunction;
import com.intellij.lang.javascript.psi.ecmal4.JSClass;
import com.intellij.lang.javascript.refactoring.ui.JSReferenceEditor;
import com.intellij.lang.javascript.ui.ActionScriptPackageChooserDialog;
import com.intellij.openapi.module.Module;
import com.intellij.openapi.project.DumbService;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.Messages;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.openapi.util.Condition;
import com.intellij.openapi.util.Conditions;
import com.intellij.openapi.util.ThrowableComputable;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.psi.PsiElement;
import com.intellij.psi.search.GlobalSearchScope;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.ButtonGroup;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class WhatToTestForm {
  private final JPanel myMainPanel; // needed for form reuse

  private final JRadioButton myPackageRadioButton;
  private final JRadioButton myClassRadioButton;
  private final JRadioButton myMethodRadioButton;

  private final JLabel myPackageOrClassLabel;
  private final JSReferenceEditor myPackageField;
  private final JSReferenceEditor myClassField;
  private final JPanel myMethodPanel;
  private final TextFieldWithBrowseButton.NoPathCompletion myMethodField;

  private final ThrowableComputable<? extends Module, ? extends RuntimeConfigurationError> myModuleComputable;
  private final ThrowableComputable<? extends FlexUnitSupport, ? extends RuntimeConfigurationError> myFlexUnitSupportComputable;
  private final TestClassFilter myMainClassFilter;

  public WhatToTestForm(final Project project,
                        final ThrowableComputable<? extends Module, ? extends RuntimeConfigurationError> moduleComputable,
                        final ThrowableComputable<? extends FlexUnitSupport, ? extends RuntimeConfigurationError> flexUnitSupportComputable) {
    myModuleComputable = moduleComputable;
    myFlexUnitSupportComputable = flexUnitSupportComputable;
    {
      myMainClassFilter = new TestClassFilter(project);
      myClassField = JSReferenceEditor.forClassName("", project, null, GlobalSearchScope.EMPTY_SCOPE, null, myMainClassFilter,
                                                    ExecutionBundle.message("choose.test.class.dialog.title"));
      myPackageField = ActionScriptPackageChooserDialog.createPackageReferenceEditor("", project, null, GlobalSearchScope.EMPTY_SCOPE,
                                                                                     ExecutionBundle.message(
                                                                                       "choose.package.dialog.title"));
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
      final JLabel label1 = new JLabel();
      label1.setText("Test:");
      myMainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
      myMainPanel.add(panel1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                                  null, 0, false));
      myClassRadioButton = new JRadioButton();
      myClassRadioButton.setText("Class or suite");
      myClassRadioButton.setMnemonic('L');
      myClassRadioButton.setDisplayedMnemonicIndex(1);
      panel1.add(myClassRadioButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                         GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                         GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myPackageRadioButton = new JRadioButton();
      myPackageRadioButton.setText("All in Package");
      myPackageRadioButton.setMnemonic('P');
      myPackageRadioButton.setDisplayedMnemonicIndex(7);
      panel1.add(myPackageRadioButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                           GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myMethodRadioButton = new JRadioButton();
      myMethodRadioButton.setText("Method");
      myMethodRadioButton.setMnemonic('T');
      myMethodRadioButton.setDisplayedMnemonicIndex(2);
      panel1.add(myMethodRadioButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                          GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer1 = new Spacer();
      panel1.add(spacer1, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                              GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      myPackageOrClassLabel = new JLabel();
      myPackageOrClassLabel.setText("Package:");
      myPackageOrClassLabel.setDisplayedMnemonic('G');
      myPackageOrClassLabel.setDisplayedMnemonicIndex(5);
      myMainPanel.add(myPackageOrClassLabel, new GridConstraints(1, 0, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                 GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null,
                                                                 null, null, 0, false));
      myMainPanel.add(myPackageField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                          null, null, 0, false));
      myMainPanel.add(myClassField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                        null, null, 0, false));
      myMethodPanel = new JPanel();
      myMethodPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
      myMainPanel.add(myMethodPanel, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                         GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                         GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                         null, null, 0, true));
      final JLabel label2 = new JLabel();
      label2.setText("Method:");
      label2.setDisplayedMnemonic('O');
      label2.setDisplayedMnemonicIndex(4);
      myMethodPanel.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                    GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                    false));
      myMethodField = new TextFieldWithBrowseButton.NoPathCompletion();
      myMethodPanel.add(myMethodField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                           null, null, null, 0, false));
      ButtonGroup buttonGroup;
      buttonGroup = new ButtonGroup();
      buttonGroup.add(myClassRadioButton);
      buttonGroup.add(myPackageRadioButton);
      buttonGroup.add(myMethodRadioButton);
    }

    final ActionListener scopeChangeListener = new ActionListener() {
      @Override
      public void actionPerformed(final ActionEvent e) {
        updateOnScopeChange();
      }
    };

    myClassRadioButton.addActionListener(scopeChangeListener);
    myPackageRadioButton.addActionListener(scopeChangeListener);
    myMethodRadioButton.addActionListener(scopeChangeListener);

    new MethodChooserActionListener(project);
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  private void updateOnScopeChange() {
    if (myClassRadioButton.isSelected()) {
      setText(myPackageOrClassLabel, "Class:", 'C');
      myMethodPanel.setVisible(false);
      myPackageOrClassLabel.setLabelFor(myClassField.getChildComponent());
      myMainClassFilter.setAllowSuite(true);
      myClassField.setVisible(true);
      myClassField.invalidateHighlight();
      myPackageField.setVisible(false);
    }
    else if (myPackageRadioButton.isSelected()) {
      setText(myPackageOrClassLabel, "Package:", 'g');
      myPackageOrClassLabel.setLabelFor(myPackageField.getChildComponent());
      myMethodPanel.setVisible(false);
      myClassField.setVisible(false);
      myPackageField.setVisible(true);
    }
    else if (myMethodRadioButton.isSelected()) {
      setText(myPackageOrClassLabel, "Class:", 'C');
      myPackageOrClassLabel.setLabelFor(myClassField.getChildComponent());
      myMethodPanel.setVisible(true);
      myMainClassFilter.setAllowSuite(false);
      myClassField.setVisible(true);
      myClassField.invalidateHighlight();
      myPackageField.setVisible(false);
    }
  }

  private static void setText(JLabel label, String text, char mnemonic) {
    label.setText(text);
    label.setDisplayedMnemonic(mnemonic);
  }

  public void updateOnBCChange(final @Nullable FlexBuildConfiguration bc, final Module module) {
    if (bc == null) {
      updateOnError(FlexBundle.message("bc.not.specified"));
      return;
    }
    final FlexUnitSupport support = FlexUnitSupport.getSupport(bc, module);
    if (support == null) {
      updateOnError(FlexBundle.message("flexunit.not.found.for.bc", bc.getName()));
      return;
    }

    updateControls(GlobalSearchScope.moduleScope(module), support);
  }

  private void updateControls(final @NotNull GlobalSearchScope scope, final @NotNull FlexUnitSupport support) {
    myClassField.setScope(scope);
    myMainClassFilter.setSupport(support);
    myClassField.setChooserBlockingMessage(null);
    myPackageField.setScope(scope);
    myPackageField.setChooserBlockingMessage(null);
  }

  public void updateOnError(final String message) {
    myClassField.setScope(GlobalSearchScope.EMPTY_SCOPE);
    myMainClassFilter.setSupport(null);
    myClassField.setChooserBlockingMessage(message);
    myPackageField.setScope(GlobalSearchScope.EMPTY_SCOPE);
    myPackageField.setChooserBlockingMessage(message);
  }

  public void resetFrom(final @Nullable Module module,
                        final @Nullable FlexBuildConfiguration bc,
                        final FlexUnitRunnerParameters params) {
    switch (params.getScope()) {
      case Class -> {
        myClassRadioButton.setSelected(true);
        myClassField.setText(params.getClassName());
        myPackageField.setText("");
      }
      case Method -> {
        myMethodRadioButton.setSelected(true);
        myClassField.setText(params.getClassName());
        myPackageField.setText("");
        myMethodField.setText(params.getMethodName());
      }
      case Package -> {
        myPackageRadioButton.setSelected(true);
        myClassField.setText("");
        myPackageField.setText(params.getPackageName());
      }
      default -> {
        assert false : "Unknown scope: " + params.getScope();
      }
    }

    updateOnBCChange(bc, module);
    updateOnScopeChange();
  }

  public void applyTo(final FlexUnitRunnerParameters params) {
    if (myClassRadioButton.isSelected()) {
      params.setScope(FlexUnitRunnerParameters.Scope.Class);
      params.setClassName(myClassField.getText());
    }
    else if (myPackageRadioButton.isSelected()) {
      params.setScope(FlexUnitRunnerParameters.Scope.Package);
      params.setPackageName(myPackageField.getText());
    }
    else if (myMethodRadioButton.isSelected()) {
      params.setScope(FlexUnitRunnerParameters.Scope.Method);
      params.setClassName(myClassField.getText());
      params.setMethodName(myMethodField.getText());
    }
  }

  public void dispose() {
  }

  private class MethodChooserActionListener extends BrowseModuleValueActionListener<JTextField> {
    protected MethodChooserActionListener(final Project project) {
      super(project);
      setField(myMethodField);
    }

    @Override
    protected String showDialog() {
      if (StringUtil.isEmpty(myClassField.getText())) {
        Messages.showInfoMessage(getProject(), ExecutionBundle.message("set.class.name.message"),
                                 ExecutionBundle.message("choose.test.method.dialog.title"));
        return null;
      }

      final Module module;
      final FlexUnitSupport support;
      try {
        module = myModuleComputable.compute();
        support = myFlexUnitSupportComputable.compute();
      }
      catch (RuntimeConfigurationError e) {
        Messages.showErrorDialog(getProject(), e.getMessage(), ExecutionBundle.message("choose.test.method.dialog.title"));
        return null;
      }

      final PsiElement clazz =
        ActionScriptClassResolver.findClassByQNameStatic(myClassField.getText(), GlobalSearchScope.moduleScope(module));
      if (!(clazz instanceof JSClass)) {
        Messages.showErrorDialog(getProject(), FlexBundle.message("class.not.found", myClassField.getText()),
                                 ExecutionBundle.message("choose.test.method.dialog.title"));
        return null;
      }

      FlexMethodChooserDialog dialog =
        new FlexMethodChooserDialog((JSClass)clazz, jsFunction -> support.isTestMethod(jsFunction), myMainPanel, myMethodField.getText());

      if (dialog.showAndGet()) {
        final JSFunction method = dialog.getSelectedMethod();
        return method != null ? method.getName() : null;
      }
      else {
        return null;
      }
    }
  }

  private static class TestClassFilter implements Condition<JSClass> {

    private final @NotNull Project myProject;
    private @Nullable FlexUnitSupport mySupport;
    private boolean myAllowSuite;

    private Condition<JSClass> myCondition;

    TestClassFilter(@NotNull Project project) {
      myProject = project;
      setSupport(null);
      setAllowSuite(false);
    }

    private synchronized Condition<JSClass> getCondition() {
      if (DumbService.getInstance(myProject).isDumb() || mySupport == null) {
        return Conditions.alwaysFalse();
      }

      if (myCondition == null) {
        myCondition = Conditions.cached(jsClass -> {
          assert mySupport != null;
          return mySupport.isTestClass(jsClass, myAllowSuite);
        });
      }
      return myCondition;
    }

    public synchronized void setSupport(@Nullable FlexUnitSupport support) {
      mySupport = support;
      myCondition = null;
    }

    public synchronized void setAllowSuite(boolean allowSuite) {
      myAllowSuite = allowSuite;
      myCondition = null;
    }

    @Override
    public boolean value(JSClass jsClass) {
      return getCondition().value(jsClass);
    }
  }
}
