// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.jetbrains.lang.dart.projectWizard;

import com.intellij.icons.AllIcons;
import com.intellij.ide.util.PropertiesComponent;
import com.intellij.ide.util.projectWizard.SettingsStep;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.ui.ComboBox;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.openapi.ui.ValidationInfo;
import com.intellij.openapi.util.Disposer;
import com.intellij.openapi.util.io.FileUtil;
import com.intellij.openapi.util.text.HtmlBuilder;
import com.intellij.openapi.util.text.HtmlChunk;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.platform.ProjectGeneratorPeer;
import com.intellij.platform.WebProjectGenerator;
import com.intellij.ui.ColorUtil;
import com.intellij.ui.ComboboxWithBrowseButton;
import com.intellij.ui.DocumentAdapter;
import com.intellij.ui.IdeBorderFactory;
import com.intellij.ui.JBColor;
import com.intellij.ui.components.JBCheckBox;
import com.intellij.ui.components.JBLabel;
import com.intellij.ui.components.JBList;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ui.AsyncProcessIcon;
import com.jetbrains.lang.dart.DartBundle;
import com.jetbrains.lang.dart.sdk.DartSdkUtil;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListModel;
import javax.swing.border.TitledBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.text.JTextComponent;
import java.awt.Component;
import java.awt.Insets;
import java.lang.reflect.Method;
import java.util.List;
import java.util.ResourceBundle;
import java.util.stream.IntStream;

public class DartGeneratorPeer implements ProjectGeneratorPeer<DartProjectWizardData> {
  private static final String DART_PROJECT_TEMPLATE = "DART_PROJECT_TEMPLATE";
  private static final String CREATE_SAMPLE_UNCHECKED = "CREATE_SAMPLE_UNCHECKED";

  private final JPanel myMainPanel;
  private final ComboboxWithBrowseButton mySdkPathComboWithBrowse;
  private final JBLabel myVersionLabel;

  private final JPanel myTemplatesPanel;
  private final JPanel myLoadingTemplatesPanel;
  private final JPanel myLoadedTemplatesPanel;
  private final JBCheckBox myCreateSampleProjectCheckBox;
  private final JBList<DartProjectTemplate> myTemplatesList;

  private final JBLabel myErrorLabel; // shown in IntelliJ IDEA only

  private boolean myIntellijLiveValidationEnabled = false;

  private boolean myDartCreateCalcStarted;
  private boolean myStagehandCalcStarted;
  private List<DartProjectTemplate> myDartCreateTemplates;// not-null means that it's been already calculated
  private List<DartProjectTemplate> myStagehandTemplates;// not-null means that it's been already calculated

  public DartGeneratorPeer() {
    // set initial values before initDartSdkControls() because listeners should not be triggered on initialization
    {
      mySdkPathComboWithBrowse = new ComboboxWithBrowseButton(new ComboBox<>());
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
      final JBLabel jBLabel1 = new JBLabel();
      this.$$$loadLabelText$$$(jBLabel1, this.$$$getMessageFromBundle$$$("messages/DartBundle", "version.label"));
      myMainPanel.add(jBLabel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                    GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                    false));
      final JBLabel jBLabel2 = new JBLabel();
      this.$$$loadLabelText$$$(jBLabel2, this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.sdk.path.label"));
      myMainPanel.add(jBLabel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                    GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                    false));
      myMainPanel.add(mySdkPathComboWithBrowse,
                      new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
                                          GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myVersionLabel = new JBLabel();
      myVersionLabel.setText("1.0");
      myMainPanel.add(myVersionLabel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                          GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                          null, 0, false));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      myTemplatesPanel = new JPanel();
      myTemplatesPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
      myTemplatesPanel.putClientProperty("BorderFactoryClass", "com.intellij.ui.IdeBorderFactory$PlainSmallWithoutIndent");
      myMainPanel.add(myTemplatesPanel, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            null, null, null, 0, false));
      myTemplatesPanel.setBorder(IdeBorderFactory.PlainSmallWithoutIndent.createTitledBorder(BorderFactory.createEtchedBorder(), null,
                                                                                             TitledBorder.DEFAULT_JUSTIFICATION,
                                                                                             TitledBorder.DEFAULT_POSITION, null, null));
      myLoadedTemplatesPanel = new JPanel();
      myLoadedTemplatesPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
      myTemplatesPanel.add(myLoadedTemplatesPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                       GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                       GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                       GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
      final JBScrollPane jBScrollPane1 = new JBScrollPane();
      myLoadedTemplatesPanel.add(jBScrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                    GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                    GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
      myTemplatesList = new JBList();
      myTemplatesList.setSelectionMode(0);
      jBScrollPane1.setViewportView(myTemplatesList);
      myCreateSampleProjectCheckBox = new JBCheckBox();
      myCreateSampleProjectCheckBox.setMargin(new Insets(2, 0, 2, 3));
      this.$$$loadButtonText$$$(myCreateSampleProjectCheckBox,
                                this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.project.generate.sample.content.label"));
      myLoadedTemplatesPanel.add(myCreateSampleProjectCheckBox,
                                 new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                     GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null,
                                                     0, false));
      myLoadingTemplatesPanel = new JPanel();
      myLoadingTemplatesPanel.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
      myTemplatesPanel.add(myLoadingTemplatesPanel,
                           new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                               null, 0, false));
      final JBLabel jBLabel3 = new JBLabel();
      this.$$$loadLabelText$$$(jBLabel3, this.$$$getMessageFromBundle$$$("messages/DartBundle", "dart.project.templates.loading.message"));
      myLoadingTemplatesPanel.add(jBLabel3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null,
                                                                null, null, 0, false));
      final Spacer spacer2 = new Spacer();
      myLoadingTemplatesPanel.add(spacer2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                               GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      final Spacer spacer3 = new Spacer();
      myLoadingTemplatesPanel.add(spacer3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                               GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      myErrorLabel = new JBLabel();
      this.$$$loadLabelText$$$(myErrorLabel, this.$$$getMessageFromBundle$$$("messages/DartBundle", "error.path.to.sdk.not.specified"));
      myMainPanel.add(myErrorLabel, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                        GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                        null, 0, false));
      jBLabel2.setLabelFor(mySdkPathComboWithBrowse);
    }
    mySdkPathComboWithBrowse.getComboBox().setEditable(true);
    //mySdkPathComboWithBrowse.getComboBox().getEditor().setItem(...); initial sdk path will be correctly taken from known paths history

    // now setup controls
    DartSdkUtil.initDartSdkControls(null, mySdkPathComboWithBrowse, myVersionLabel);

    myCreateSampleProjectCheckBox.addActionListener(e -> myTemplatesList.setEnabled(myCreateSampleProjectCheckBox.isSelected()));
    String selectedTemplateName = PropertiesComponent.getInstance().getValue(DART_PROJECT_TEMPLATE);
    myCreateSampleProjectCheckBox.setSelected(!CREATE_SAMPLE_UNCHECKED.equals(selectedTemplateName));

    myTemplatesList.setEmptyText(DartBundle.message("set.sdk.to.see.sample.content.options"));

    myTemplatesList.setCellRenderer(new DefaultListCellRenderer() {
      @Override
      public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        JLabel component = (JLabel)super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        DartProjectTemplate template = (DartProjectTemplate)value;
        String text = template.getDescription().isEmpty()
                      ? template.getName()
                      : template.getName() + " - " + StringUtil.decapitalize(template.getDescription());
        component.setText(text);
        return component;
      }
    });

    myErrorLabel.setIcon(AllIcons.Actions.Lightning);
    myErrorLabel.setVisible(false);

    myLoadingTemplatesPanel.setVisible(false);
    myCreateSampleProjectCheckBox.setEnabled(false);
    myTemplatesList.setEnabled(false);

    final JTextComponent editorComponent = (JTextComponent)mySdkPathComboWithBrowse.getComboBox().getEditor().getEditorComponent();
    editorComponent.getDocument().addDocumentListener(new DocumentAdapter() {
      @Override
      protected void textChanged(final @NotNull DocumentEvent e) {
        final String sdkPath = mySdkPathComboWithBrowse.getComboBox().getEditor().getItem().toString().trim();
        final String message = DartSdkUtil.getErrorMessageIfWrongSdkRootPath(sdkPath);
        if (message == null) {
          onSdkPathChanged();
        }
      }
    });

    onSdkPathChanged();
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  private void onSdkPathChanged() {
    String sdkPath = mySdkPathComboWithBrowse.getComboBox().getEditor().getItem().toString().trim();
    String errorMessage = DartSdkUtil.getErrorMessageIfWrongSdkRootPath(sdkPath);
    if (errorMessage != null) {
      myLoadingTemplatesPanel.setVisible(false);
      myTemplatesPanel.setVisible(false);
      return;
    }

    boolean useDartCreate = Stagehand.isUseDartCreate(sdkPath);
    if (useDartCreate) {
      if (myDartCreateCalcStarted) {
        if (myDartCreateTemplates != null) {
          showTemplates(myDartCreateTemplates);
        }
        else {
          // Calculation in progress, just wait.
          myLoadingTemplatesPanel.setVisible(true);
          myLoadedTemplatesPanel.setVisible(false);
        }
      }
      else {
        myDartCreateCalcStarted = true;
        startLoadingTemplates(useDartCreate);
      }
    }
    else {
      if (myStagehandCalcStarted) {
        if (myStagehandTemplates != null) {
          showTemplates(myStagehandTemplates);
        }
        else {
          // Calculation in progress, just wait.
          myLoadingTemplatesPanel.setVisible(true);
          myLoadedTemplatesPanel.setVisible(false);
        }
      }
      else {
        myStagehandCalcStarted = true;
        startLoadingTemplates(useDartCreate);
      }
    }
  }

  private void startLoadingTemplates(boolean useDartCreate) {
    myLoadingTemplatesPanel.setVisible(true);
    myLoadingTemplatesPanel.setPreferredSize(myLoadedTemplatesPanel.getPreferredSize());

    myLoadedTemplatesPanel.setVisible(false);

    final AsyncProcessIcon asyncProcessIcon = new AsyncProcessIcon("Dart project templates loading");
    myLoadingTemplatesPanel.add(asyncProcessIcon, new GridConstraints());  // defaults are ok: row = 0, column = 0
    asyncProcessIcon.resume();

    ApplicationManager.getApplication().executeOnPooledThread(() -> {
      final String sdkPath =
        FileUtil.toSystemIndependentName(mySdkPathComboWithBrowse.getComboBox().getEditor().getItem().toString().trim());
      DartProjectTemplate.loadTemplatesAsync(sdkPath, templates -> {
        asyncProcessIcon.suspend();
        myLoadingTemplatesPanel.remove(asyncProcessIcon);
        Disposer.dispose(asyncProcessIcon);

        if (useDartCreate) {
          myDartCreateTemplates = templates;
        }
        else {
          myStagehandTemplates = templates;
        }

        // it's better to call onSdkPathChanged() but not showTemplates() directly as sdk path could have been changed during this long calculation
        onSdkPathChanged();
      });
    });
  }

  private void showTemplates(final List<DartProjectTemplate> templates) {
    ListModel<DartProjectTemplate> currentModel = myTemplatesList.getModel();

    if (myLoadedTemplatesPanel.isVisible() &&
        currentModel.getSize() == templates.size() &&
        IntStream.range(0, templates.size()).allMatch(i -> templates.get(i).getName().equals(currentModel.getElementAt(i).getName()))) {
      // already showing the right list
      return;
    }

    boolean rightAfterLoading = myLoadingTemplatesPanel.isVisible();

    myLoadingTemplatesPanel.setVisible(false);
    myLoadedTemplatesPanel.setVisible(true);
    myCreateSampleProjectCheckBox.setEnabled(true);

    final String selectedTemplateName = PropertiesComponent.getInstance().getValue(DART_PROJECT_TEMPLATE);

    myTemplatesList.setVisibleRowCount(Math.min(8, templates.size()));
    myTemplatesList.setEnabled(myCreateSampleProjectCheckBox.isSelected());

    DartProjectTemplate selectedTemplate = null;

    final DefaultListModel<DartProjectTemplate> model = new DefaultListModel<>();
    for (DartProjectTemplate template : templates) {
      model.addElement(template);

      if (rightAfterLoading && template.getName().equals(selectedTemplateName)) {
        selectedTemplate = template;
      }
    }

    myTemplatesList.setModel(model);

    if (selectedTemplate != null) {
      myTemplatesList.setSelectedValue(selectedTemplate, true);
    }
    else if (!templates.isEmpty()) {
      myTemplatesList.setSelectedIndex(0);
    }
  }

  @Override
  public @NotNull JComponent getComponent(@NotNull TextFieldWithBrowseButton myLocationField, @NotNull Runnable checkValid) {
    return myMainPanel;
  }

  @NotNull
  JPanel getMainPanel() {
    return myMainPanel;
  }

  @Override
  public void buildUI(final @NotNull SettingsStep settingsStep) {
    settingsStep.addSettingsField(DartBundle.message("dart.sdk.path.label"), mySdkPathComboWithBrowse);
    settingsStep.addSettingsField(DartBundle.message("version.label"), myVersionLabel);
    settingsStep.addSettingsComponent(myTemplatesPanel);
  }

  @Override
  public @NotNull DartProjectWizardData getSettings() {
    final String sdkPath = FileUtil.toSystemIndependentName(mySdkPathComboWithBrowse.getComboBox().getEditor().getItem().toString().trim());
    final DartProjectTemplate template = myCreateSampleProjectCheckBox.isSelected() ? myTemplatesList.getSelectedValue() : null;
    PropertiesComponent.getInstance().setValue(DART_PROJECT_TEMPLATE, template == null ? CREATE_SAMPLE_UNCHECKED : template.getName());

    return new DartProjectWizardData(sdkPath, template);
  }

  @Override
  public @Nullable ValidationInfo validate() {
    final String sdkPath = mySdkPathComboWithBrowse.getComboBox().getEditor().getItem().toString().trim();
    final String message = DartSdkUtil.getErrorMessageIfWrongSdkRootPath(sdkPath);
    if (message != null) {
      return new ValidationInfo(message, mySdkPathComboWithBrowse);
    }

    if (myCreateSampleProjectCheckBox.isSelected()) {
      if (myTemplatesList.getSelectedValue() == null) {
        return new ValidationInfo(DartBundle.message("project.template.not.selected"), myCreateSampleProjectCheckBox);
      }
    }

    return null;
  }

  public boolean validateInIntelliJ() {
    final ValidationInfo info = validate();

    if (info == null) {
      myErrorLabel.setVisible(false);
      return true;
    }
    else {
      myErrorLabel.setVisible(true);
      HtmlChunk.Element html = new HtmlBuilder().append(info.message)
        .wrapWith("font").attr("color", "#" + ColorUtil.toHex(JBColor.RED))
        .wrapWith("html");
      myErrorLabel.setText(html.toString());

      if (!myIntellijLiveValidationEnabled) {
        myIntellijLiveValidationEnabled = true;
        enableIntellijLiveValidation();
      }

      return false;
    }
  }

  private void enableIntellijLiveValidation() {
    final JTextComponent editorComponent = (JTextComponent)mySdkPathComboWithBrowse.getComboBox().getEditor().getEditorComponent();
    editorComponent.getDocument().addDocumentListener(new DocumentAdapter() {
      @Override
      protected void textChanged(final @NotNull DocumentEvent e) {
        validateInIntelliJ();
      }
    });

    myCreateSampleProjectCheckBox.addActionListener(e -> validateInIntelliJ());

    myTemplatesList.addListSelectionListener(e -> validateInIntelliJ());
  }

  @Override
  public boolean isBackgroundJobRunning() {
    return false;
  }

  @Override
  public void addSettingsStateListener(final @NotNull WebProjectGenerator.SettingsStateListener stateListener) {
    final JTextComponent editorComponent = (JTextComponent)mySdkPathComboWithBrowse.getComboBox().getEditor().getEditorComponent();
    editorComponent.getDocument().addDocumentListener(new DocumentAdapter() {
      @Override
      protected void textChanged(final @NotNull DocumentEvent e) {
        stateListener.stateChanged(validate() == null);
      }
    });

    myCreateSampleProjectCheckBox.addActionListener(e -> stateListener.stateChanged(validate() == null));

    myTemplatesList.addListSelectionListener(e -> stateListener.stateChanged(validate() == null));
  }
}
