package com.intellij.lang.javascript.flex.projectStructure.detection;

import com.intellij.ide.util.projectWizard.ModuleWizardStep;
import com.intellij.ide.util.projectWizard.WizardContext;
import com.intellij.lang.javascript.flex.FlexBundle;
import com.intellij.lang.javascript.flex.FlexModuleType;
import com.intellij.lang.javascript.flex.projectStructure.FlexBuildConfigurationsExtension;
import com.intellij.lang.javascript.flex.projectStructure.model.FlexBuildConfiguration;
import com.intellij.lang.javascript.flex.projectStructure.model.FlexBuildConfigurationManager;
import com.intellij.lang.javascript.flex.projectStructure.model.ModifiableFlexBuildConfiguration;
import com.intellij.lang.javascript.flex.projectStructure.model.SdkEntry;
import com.intellij.lang.javascript.flex.projectStructure.model.impl.FlexProjectConfigurationEditor;
import com.intellij.lang.javascript.flex.sdk.FlexSdkComboBoxWithBrowseButton;
import com.intellij.lang.javascript.flex.sdk.FlexSdkType2;
import com.intellij.lang.javascript.flex.sdk.FlexSdkUtils;
import com.intellij.openapi.module.Module;
import com.intellij.openapi.module.ModuleManager;
import com.intellij.openapi.module.ModuleType;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.projectRoots.Sdk;
import com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ui.UIUtil;
import org.jetbrains.annotations.Nullable;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Insets;

public class FlexSdkStep extends ModuleWizardStep {
  private final JPanel myContentPane;
  private final FlexSdkComboBoxWithBrowseButton mySdkCombo;
  private final JLabel mySdkLabel;
  private final WizardContext myContext;

  public FlexSdkStep(WizardContext context) {
    myContext = context;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myContentPane = new JPanel();
      myContentPane.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
      mySdkLabel = new JLabel();
      mySdkLabel.setText("Project SDK:");
      myContentPane.add(mySdkLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                        GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                        null, 0, false));
      final Spacer spacer1 = new Spacer();
      myContentPane.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                     GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      mySdkCombo = new FlexSdkComboBoxWithBrowseButton();
      myContentPane.add(mySdkCombo, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                        null, null, 0, false));
    }
    selectSdkUsedByOtherModules(myContext.getProject(), mySdkCombo);
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myContentPane; }

  @Override
  public JComponent getComponent() {
    mySdkLabel.setLabelFor(mySdkCombo.getChildComponent());
    final String text = FlexBundle.message(myContext.getProject() != null ? "module.sdk.label" : "project.sdk.label");
    mySdkLabel.setText(UIUtil.removeMnemonic(text));
    mySdkLabel.setDisplayedMnemonicIndex(UIUtil.getDisplayMnemonicIndex(text));

    mySdkCombo.setButtonEnabled(FlexBuildConfigurationsExtension.getInstance().getConfigurator().getConfigEditor() == null);
    return myContentPane;
  }

  @Override
  public void updateDataModel() {
    myContext.setProjectJdk(mySdkCombo.getSelectedSdk());
  }

  private static void selectSdkUsedByOtherModules(final @Nullable Project project, final FlexSdkComboBoxWithBrowseButton combo) {
    if (project == null) {
      return;
    }

    final FlexProjectConfigurationEditor currentEditor = FlexBuildConfigurationsExtension.getInstance().getConfigurator().getConfigEditor();
    if (currentEditor != null) {
      final Module[] modules = ProjectStructureConfigurable.getInstance(project).getModulesConfig().getModules();
      for (Module module : modules) {
        if (ModuleType.get(module) != FlexModuleType.getInstance()) {
          continue;
        }
        for (ModifiableFlexBuildConfiguration c : currentEditor.getConfigurations(module)) {
          SdkEntry sdkEntry = c.getDependencies().getSdkEntry();
          Sdk sdk;
          if (sdkEntry != null &&
              (sdk = FlexSdkUtils.findFlexOrFlexmojosSdk(sdkEntry.getName())) != null &&
              sdk.getSdkType() == FlexSdkType2.getInstance()) {
            combo.setSelectedSdkRaw(sdk.getName());
            return;
          }
        }
      }
    }
    else {
      for (final Module module : ModuleManager.getInstance(project).getModules()) {
        if (ModuleType.get(module) == FlexModuleType.getInstance()) {
          for (FlexBuildConfiguration bc : FlexBuildConfigurationManager.getInstance(module).getBuildConfigurations()) {
            Sdk sdk = bc.getSdk();
            if (sdk != null) {
              combo.setSelectedSdkRaw(sdk.getName());
              return;
            }
          }
        }
      }
    }
  }
}
