// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.javascript.flex.refactoring.introduceConstant;

import com.intellij.ide.util.PlatformPackageUtil;
import com.intellij.lang.javascript.psi.JSElement;
import com.intellij.lang.javascript.psi.JSExpression;
import com.intellij.lang.javascript.psi.ecmal4.JSClass;
import com.intellij.lang.javascript.psi.resolve.JSResolveUtil;
import com.intellij.lang.javascript.refactoring.introduce.BasicIntroducedEntityInfoProvider;
import com.intellij.lang.javascript.refactoring.introduce.JSBaseClassBasedIntroduceDialog;
import com.intellij.lang.javascript.refactoring.introduce.JSBaseIntroduceHandler;
import com.intellij.lang.javascript.refactoring.ui.JSReferenceEditor;
import com.intellij.lang.javascript.refactoring.ui.JSVisibilityPanel;
import com.intellij.openapi.editor.event.DocumentEvent;
import com.intellij.openapi.editor.event.DocumentListener;
import com.intellij.openapi.module.Module;
import com.intellij.openapi.module.ModuleUtilCore;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.psi.PsiDirectory;
import com.intellij.psi.PsiElement;
import com.intellij.psi.search.GlobalSearchScope;
import com.intellij.refactoring.RefactoringBundle;
import com.intellij.refactoring.ui.NameSuggestionsField;
import com.intellij.ui.EditorComboBox;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.NotNull;

import javax.swing.Action;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Insets;
import java.lang.reflect.Method;
import java.util.ResourceBundle;

/**
 * @author Maxim.Mossienko
 */
public class FlexIntroduceConstantDialog extends JSBaseClassBasedIntroduceDialog<BasicIntroducedEntityInfoProvider>
  implements FlexIntroduceConstantSettings {
  public static final String RECENT_KEY = "FlexIntroduceConstantDialog";
  private final NameSuggestionsField myNameField;
  private final JCheckBox myReplaceAllCheckBox;
  private final JPanel myPanel;
  private final EditorComboBox myVarType;
  private final JLabel myNameLabel;
  private final JLabel myTargetClassLabel;
  private final JSVisibilityPanel myVisibilityPanel;
  private final JPanel myTargetClassPanel;
  private final JSReferenceEditor myTargetClassField;

  protected FlexIntroduceConstantDialog(final Project project,
                                        final JSExpression[] occurrences,
                                        final JSExpression mainOccurrence,
                                        PsiElement scope) {
    super(
      project,
      new IntroduceConstantInfoProvider(mainOccurrence, occurrences, scope),
      "javascript.introduce.constant.title"
    );
    {
      myNameField = configureNameField();
      myVarType = configureTypeField();
      myVisibilityPanel = new JSVisibilityPanel();
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myPanel = new JPanel();
      myPanel.setLayout(new GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
      myReplaceAllCheckBox = new JCheckBox();
      myReplaceAllCheckBox.setActionCommand("");
      myReplaceAllCheckBox.setContentAreaFilled(false);
      myReplaceAllCheckBox.setFocusable(false);
      myReplaceAllCheckBox.setMargin(new Insets(2, 0, 2, 3));
      myReplaceAllCheckBox.setText("");
      myPanel.add(myReplaceAllCheckBox, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myPanel.add(myVarType, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                 GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                 new Dimension(150, -1), null, 0, false));
      final JLabel label1 = new JLabel();
      this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("messages/JavaScriptBundle", "extract.constant.type"));
      myPanel.add(label1,
                  new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                      GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myNameLabel = new JLabel();
      myNameLabel.setRequestFocusEnabled(false);
      this.$$$loadLabelText$$$(myNameLabel,
                               this.$$$getMessageFromBundle$$$("messages/JavaScriptBundle", "javascript.introduce.variable.name.prompt"));
      myPanel.add(myNameLabel,
                  new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                      GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myPanel.add(myNameField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null,
                                                   new Dimension(150, -1), null, 0, false));
      myTargetClassLabel = new JLabel();
      this.$$$loadLabelText$$$(myTargetClassLabel,
                               this.$$$getMessageFromBundle$$$("messages/JavaScriptBundle", "introduce.constant.target.class"));
      myPanel.add(myTargetClassLabel,
                  new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                      GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myPanel.add(myVisibilityPanel, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                         GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                         GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                         null, null, 0, false));
      myTargetClassPanel = new JPanel();
      myTargetClassPanel.setLayout(new BorderLayout(0, 0));
      myPanel.add(myTargetClassPanel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                          null, null, 0, false));
      final Spacer spacer1 = new Spacer();
      myPanel.add(spacer1, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                               GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      label1.setLabelFor(myVarType);
    }

    JSElement classAnchor = JSBaseIntroduceHandler.findClassAnchor(mainOccurrence);
    String initialText = classAnchor instanceof JSClass ? ((JSClass)classAnchor).getQualifiedName() : "";
    Module module = ModuleUtilCore.findModuleForPsiElement(mainOccurrence);
    GlobalSearchScope targetClassScope =
      module != null ? GlobalSearchScope.moduleWithDependenciesScope(module) : GlobalSearchScope.projectScope(project);
    PsiDirectory dir = PlatformPackageUtil.getDirectory(mainOccurrence);
    targetClassScope = PlatformPackageUtil.adjustScope(dir, targetClassScope, false, true);
    myTargetClassField = createTargetClassField(project, initialText, targetClassScope);
    myTargetClassPanel.add(myTargetClassField, BorderLayout.CENTER);
    myTargetClassLabel.setLabelFor(myTargetClassField.getChildComponent());
    myTargetClassField.addDocumentListener(new DocumentListener() {
      @Override
      public void documentChanged(@NotNull DocumentEvent e) {
        initiateValidation();
      }
    });
    doInit();
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myPanel; }

  public static JSReferenceEditor createTargetClassField(Project project, String initialText, GlobalSearchScope scope) {
    return JSReferenceEditor.forClassName(initialText, project, RECENT_KEY, scope, null, null,
                                          RefactoringBundle.message("choose.destination.class"));
  }

  @Override
  protected void checkIsValid() {
    super.checkIsValid();
    Action action = getOKAction();
    String className = getClassName();
    PsiElement clazz = null;
    action.setEnabled(action.isEnabled() &&
                      (StringUtil.isEmpty(className) ||
                       (clazz = JSResolveUtil.findType(className, entityInfoProvider.myMainOccurrence, true)) instanceof JSClass));
    if (clazz == null) {
      JSElement element = JSBaseIntroduceHandler.findClassAnchor(entityInfoProvider.myMainOccurrence);
      clazz = element != null ? JSResolveUtil.findParent(element) : null;
    }

    if (clazz instanceof JSClass) {
      checkUniqueness(clazz);
    }
  }

  @Override
  protected JSVisibilityPanel getVisibilityPanel() {
    return myVisibilityPanel;
  }

  @Override
  protected NameSuggestionsField getNameField() {
    return myNameField;
  }

  @Override
  protected JLabel getNameLabel() {
    return myNameLabel;
  }

  @Override
  protected JPanel getPanel() {
    return myPanel;
  }

  @Override
  protected JCheckBox getReplaceAllCheckBox() {
    return myReplaceAllCheckBox;
  }

  @Override
  public JComboBox getVarTypeField() {
    return myVarType;
  }

  @Override
  public String getClassName() {
    return myTargetClassField.getText();
  }

  @Override
  protected void doOKAction() {
    myTargetClassField.updateRecents();
    super.doOKAction();
  }

  @Override
  protected String getHelpId() {
    return "refactoring.introduceConstant.ActionScript";
  }
}
