// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.lang.javascript.flex.sdk;

import com.intellij.openapi.fileChooser.FileChooserDescriptor;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.projectRoots.AdditionalDataConfigurable;
import com.intellij.openapi.projectRoots.Sdk;
import com.intellij.openapi.ui.LabeledComponentNoThrow;
import com.intellij.openapi.ui.TextComponentAccessor;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.openapi.util.io.FileUtil;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.NotNull;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.awt.Dimension;
import java.awt.Insets;
import java.util.Collection;
import java.util.Collections;

public class FlexmojosSdkDataConfigurable implements AdditionalDataConfigurable {
  private Sdk mySdk;
  private final FlexmojosSdkForm myFlexmojosSdkForm;

  public FlexmojosSdkDataConfigurable() {
    myFlexmojosSdkForm = new FlexmojosSdkForm();
  }

  @Override
  public void setSdk(final Sdk sdk) {
    mySdk = sdk;
  }

  @Override
  public JComponent createComponent() {
    return myFlexmojosSdkForm.getMainPanel();
  }

  @Override
  public boolean isModified() {
    final FlexmojosSdkAdditionalData data = (FlexmojosSdkAdditionalData)mySdk.getSdkAdditionalData();
    if (data != null) {
      if (!myFlexmojosSdkForm.getAdlPath().equals(data.getAdlPath())) return true;
      if (!myFlexmojosSdkForm.getAirRuntimePath().equals(data.getAirRuntimePath())) return true;
    }
    return false;
  }

  @Override
  public void apply() throws ConfigurationException {
    final FlexmojosSdkAdditionalData data = (FlexmojosSdkAdditionalData)mySdk.getSdkAdditionalData();
    if (data != null) {
      data.setAdlPath(myFlexmojosSdkForm.getAdlPath());
      data.setAirRuntimePath(myFlexmojosSdkForm.getAirRuntimePath());
    }
  }

  @Override
  public void reset() {
    final FlexmojosSdkAdditionalData data = (FlexmojosSdkAdditionalData)mySdk.getSdkAdditionalData();
    myFlexmojosSdkForm.setFlexCompilerClasspath(data == null ? Collections.emptyList() : data.getFlexCompilerClasspath());
    myFlexmojosSdkForm.setAdlPath(data == null ? "" : data.getAdlPath());
    myFlexmojosSdkForm.setAirRuntimePath(data == null ? "" : data.getAirRuntimePath());
  }

  private static final class FlexmojosSdkForm {
    private final JComponent myMainPanel;
    private final JTextArea myClasspathTextArea;
    private final LabeledComponentNoThrow<TextFieldWithBrowseButton> myAdlComponent;
    private final LabeledComponentNoThrow<TextFieldWithBrowseButton> myAirRuntimeComponent;

    private FlexmojosSdkForm() {
      {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        myMainPanel = new JPanel();
        myMainPanel.setLayout(new GridLayoutManager(5, 1, new Insets(1, 3, 1, 3), -1, 10));
        final Spacer spacer1 = new Spacer();
        myMainPanel.add(spacer1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                     GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        myMainPanel.add(separator1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                        GridConstraints.SIZEPOLICY_FIXED,
                                                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
                                                        new Dimension(-1, 10), null, null, 0, false));
        myAdlComponent = new LabeledComponentNoThrow();
        myAdlComponent.setComponentClass("com.intellij.openapi.ui.TextFieldWithBrowseButton");
        myAdlComponent.setText("AIR De&bug Launcher");
        myMainPanel.add(myAdlComponent, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            null,
                                                            null, null, 0, false));
        myAirRuntimeComponent = new LabeledComponentNoThrow();
        myAirRuntimeComponent.setComponentClass("com.intellij.openapi.ui.TextFieldWithBrowseButton");
        myAirRuntimeComponent.setText("AIR &Runtime (directory or zip file)");
        myMainPanel.add(myAirRuntimeComponent,
                        new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                            GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                            GridConstraints.SIZEPOLICY_CAN_GROW,
                                            GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                            GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, 0));
        myMainPanel.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                                    null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Flex Compiler/Debugger Classpath:");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                               null,
                                               0, false));
        final JBScrollPane jBScrollPane1 = new JBScrollPane();
        panel1.add(jBScrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                      GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
                                                      GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        myClasspathTextArea = new JTextArea();
        myClasspathTextArea.setEditable(false);
        myClasspathTextArea.setLineWrap(false);
        myClasspathTextArea.setRows(5);
        myClasspathTextArea.setWrapStyleWord(false);
        jBScrollPane1.setViewportView(myClasspathTextArea);
      }
      initAdlChooser();
      initAirRuntimeChooser();
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() { return myMainPanel; }

    private void initAdlChooser() {
      final FileChooserDescriptor descriptor = new FileChooserDescriptor(true, false, false, false, false, false)
        .withTitle("Select ADL executable file");

      myAdlComponent.getComponent()
        .addBrowseFolderListener(null, descriptor, new TextComponentAccessor<>() {
          @Override
          public void setText(final JTextField component, final @NotNull String text) {
            component.setText(text);
            final String adlPath = FileUtil.toSystemDependentName(text);
            if (adlPath.endsWith(FlexSdkUtils.ADL_RELATIVE_PATH)) {
              final String runtimePath =
                adlPath.substring(0, adlPath.length() - FlexSdkUtils.ADL_RELATIVE_PATH.length()) + FlexSdkUtils.AIR_RUNTIME_RELATIVE_PATH;
              myAirRuntimeComponent.getComponent().setText(runtimePath);
            }
          }

          @Override
          public String getText(final JTextField component) {
            return component.getText();
          }
        });
    }

    private void initAirRuntimeChooser() {
      var descriptor = new FileChooserDescriptor(true, true, true, false, false, false)
        .withExtensionFilter("zip")
        .withTitle("Select AIR Runtime")
        .withDescription("Select AIR Runtime as a directory like <Flex SDK>/runtimes/AIR/win/ or as a .zip file");
      TextFieldWithBrowseButton button = myAirRuntimeComponent.getComponent();
      button.addBrowseFolderListener(null, descriptor);
    }

    JComponent getMainPanel() {
      return myMainPanel;
    }

    void setFlexCompilerClasspath(final Collection<String> classpathEntries) {
      myClasspathTextArea.setText(StringUtil.join(classpathEntries, s -> FileUtil.toSystemDependentName(s), "\n"));
    }

    void setAdlPath(final String adlPath) {
      myAdlComponent.getComponent().setText(FileUtil.toSystemDependentName(adlPath));
    }

    String getAdlPath() {
      return FileUtil.toSystemIndependentName(myAdlComponent.getComponent().getText().trim());
    }

    void setAirRuntimePath(final String airRuntimePath) {
      myAirRuntimeComponent.getComponent().setText(FileUtil.toSystemDependentName(airRuntimePath));
    }

    String getAirRuntimePath() {
      return FileUtil.toSystemIndependentName(myAirRuntimeComponent.getComponent().getText().trim());
    }
  }
}
