// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.lang.javascript.uml.actions;

import com.intellij.lang.javascript.DialectDetector;
import com.intellij.lang.javascript.JavaScriptBundle;
import com.intellij.lang.javascript.flex.FlexSupportLoader;
import com.intellij.lang.javascript.parsing.JavaScriptParserBase;
import com.intellij.lang.javascript.psi.JSElementFactory;
import com.intellij.lang.javascript.psi.JSExpressionCodeFragment;
import com.intellij.lang.javascript.psi.ecmal4.JSAttributeList;
import com.intellij.lang.javascript.psi.ecmal4.JSClass;
import com.intellij.lang.javascript.psi.impl.JSChangeUtil;
import com.intellij.lang.javascript.refactoring.ui.JSEditorTextField;
import com.intellij.lang.javascript.refactoring.ui.JSReferenceEditor;
import com.intellij.lang.javascript.refactoring.ui.JSVisibilityPanel;
import com.intellij.lang.javascript.refactoring.util.JSRefactoringUtil;
import com.intellij.openapi.editor.Document;
import com.intellij.openapi.module.Module;
import com.intellij.openapi.module.ModuleUtilCore;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.ui.Messages;
import com.intellij.openapi.util.Pair;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.psi.PsiCodeFragment;
import com.intellij.psi.PsiDocumentManager;
import com.intellij.psi.search.GlobalSearchScope;
import com.intellij.ui.EditorTextField;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Dimension;
import java.awt.Insets;

public class JSCreateFieldDialog extends DialogWrapper {
  private final JSReferenceEditor myTypeField;
  private final JLabel myTypeLabel;
  private final EditorTextField myNameField;
  private final JCheckBox myDeclareStaticCb;
  private final JPanel myContentPane;
  private final JSVisibilityPanel myVisibilityPanel;
  private final JLabel myNameLabel;
  private final EditorTextField myInitializerField;
  private final JLabel myInitializerLabel;
  private final JCheckBox myDeclareConstantCb;
  private final JSClass myTargetClass;

  private static boolean ourDeclareConstant;
  private static boolean ourDeclareStatic;

  public JSCreateFieldDialog(JSClass clazz) {
    super(clazz.getProject(), true);
    myTargetClass = clazz;
    {
      java.lang.Module module = ModuleUtilCore.findModuleForPsiElement(myTargetClass);
      GlobalSearchScope scope = getTypeFieldScope(module, myTargetClass.getProject());
      myTypeField = createTypeField(myTargetClass.getProject(), scope);

      myVisibilityPanel = new JSVisibilityPanel();

      PsiCodeFragment initializerCodeFragment = createInitializerCodeFragment(myTargetClass);
      Document document = PsiDocumentManager.getInstance(myTargetClass.getProject()).getDocument(initializerCodeFragment);
      myInitializerField = new JSEditorTextField(myTargetClass.getProject(), document);
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myContentPane = new JPanel();
      myContentPane.setLayout(new GridLayoutManager(7, 2, new Insets(0, 0, 0, 0), -1, -1));
      myNameLabel = new JLabel();
      myNameLabel.setText("Name:");
      myNameLabel.setDisplayedMnemonic('N');
      myNameLabel.setDisplayedMnemonicIndex(0);
      myContentPane.add(myNameLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                         GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                         null, 0, false));
      myTypeLabel = new JLabel();
      myTypeLabel.setText("Type:");
      myTypeLabel.setDisplayedMnemonic('T');
      myTypeLabel.setDisplayedMnemonicIndex(0);
      myContentPane.add(myTypeLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                         GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                         null, 0, false));
      myContentPane.add(myTypeField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                         GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                         GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                         new Dimension(300, -1), null, null, 0, false));
      myNameField = new EditorTextField();
      myContentPane.add(myNameField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                         GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                         GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
      myContentPane.add(myVisibilityPanel, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                               null, null, null, 0, false));
      myDeclareStaticCb = new JCheckBox();
      myDeclareStaticCb.setText("Declare static");
      myDeclareStaticCb.setMnemonic('S');
      myDeclareStaticCb.setDisplayedMnemonicIndex(8);
      myContentPane.add(myDeclareStaticCb, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                               GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer1 = new Spacer();
      myContentPane.add(spacer1, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                     GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      myInitializerLabel = new JLabel();
      myInitializerLabel.setText("Initializer:");
      myInitializerLabel.setDisplayedMnemonic('A');
      myInitializerLabel.setDisplayedMnemonicIndex(5);
      myContentPane.add(myInitializerLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null,
                                                                null, null, 0, false));
      myContentPane.add(myInitializerField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
      myDeclareConstantCb = new JCheckBox();
      myDeclareConstantCb.setText("Declare constant");
      myDeclareConstantCb.setMnemonic('C');
      myDeclareConstantCb.setDisplayedMnemonicIndex(8);
      myContentPane.add(myDeclareConstantCb, new GridConstraints(5, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                 GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                 GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                 null, null, null, 0, false));
    }

    setTitle(JavaScriptBundle.message("create.field.dialog.title"));
    myVisibilityPanel.configureForClassMember(false, false, DialectDetector.dialectOfElement(clazz));
    myVisibilityPanel.setVisibility(JSAttributeList.AccessType.PRIVATE.name());
    myTypeLabel.setLabelFor(myTypeField.getChildComponent());
    myNameLabel.setLabelFor(myNameField);
    myInitializerLabel.setLabelFor(myInitializerField);

    myDeclareConstantCb.setSelected(ourDeclareConstant);
    myDeclareStaticCb.setSelected(ourDeclareStatic);
    init();
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myContentPane; }

  public static GlobalSearchScope getTypeFieldScope(@Nullable Module module, @NotNull Project project) {
    return module != null
           ? GlobalSearchScope.moduleWithDependenciesAndLibrariesScope(module)
           : GlobalSearchScope.allScope(project);
  }

  public static JSReferenceEditor createTypeField(Project project, GlobalSearchScope scope) {
    return JSReferenceEditor.forClassName("", project, "JSCreateFieldDialog", scope, JavaScriptParserBase.ForceContext.Type, null,
                                          JavaScriptBundle.message("choose.field.type"));
  }

  public static JSExpressionCodeFragment createInitializerCodeFragment(JSClass c) {
    return JSElementFactory.createExpressionCodeFragment(c.getProject(), "", c, FlexSupportLoader.ECMA_SCRIPT_L4,
                                                         c.getResolveScope(), JSElementFactory.TopLevelCompletion.LITERAL_VALUES, null);
  }

  @Override
  protected JComponent createCenterPanel() {
    return myContentPane;
  }

  @Override
  public JComponent getPreferredFocusedComponent() {
    return myTypeField.getChildComponent();
  }

  public String getFieldName() {
    return myNameField.getText();
  }

  public String getFieldType() {
    return myTypeField.getText();
  }

  public boolean isStatic() {
    return myDeclareStaticCb.isSelected();
  }

  public String getVisibility() {
    return myVisibilityPanel.getVisibility();
  }

  /**
   * @return pair(message, isFatal)
   */
  private @Nullable Pair<String, Boolean> validateData() {
    if (!JSRefactoringUtil.isValidIdentifier(getFieldName(), myTargetClass.getProject())) {
      return Pair.create(JavaScriptBundle.message("invalid.identifier.value.0", getFieldName()), true);
    }
    String type = getFieldType().trim();
    if ("void".equals(type) || type.contains(" ") || JSChangeUtil.tryCreateTypeElement(type, myTargetClass) == null) {
      return Pair.create(JavaScriptBundle.message("invalid.field.type.expression", type), true);
    }
    if (isConstant() && StringUtil.isEmpty(getInitializer())) {
      return Pair.create(JavaScriptBundle.message("field.initializer.is.not.specified"), true);
    }
    if (!JSRefactoringUtil.isResolvableType(type, myTargetClass, false, false)) {
      return Pair.create(JavaScriptBundle.message("type.is.not.resolved", type), false);
    }
    if (myTargetClass.findFieldByName(getFieldName()) != null) {
      return Pair.create(JavaScriptBundle.message("class.already.contains.field.warning", myTargetClass.getQualifiedName(), getFieldName()),
                         false);
    }
    return null;
  }

  public boolean isConstant() {
    return myDeclareConstantCb.isSelected();
  }

  public String getInitializer() {
    return myInitializerField.getText();
  }

  @Override
  protected String getDimensionServiceKey() {
    return "JSCreateFieldDialog";
  }

  @Override
  protected void doOKAction() {
    Pair<String, Boolean> errorStatus = validateData();
    if (errorStatus != null) {
      if (errorStatus.second) {
        Messages.showErrorDialog(myContentPane, errorStatus.first, getTitle());
        return;
      }
      else {
        if (Messages.showYesNoDialog(myContentPane, errorStatus.first, getTitle(), Messages.getQuestionIcon()) != Messages.YES) {
          return;
        }
      }
    }
    myTypeField.updateRecents();
    //noinspection AssignmentToStaticFieldFromInstanceMethod
    ourDeclareConstant = myDeclareConstantCb.isSelected();
    //noinspection AssignmentToStaticFieldFromInstanceMethod
    ourDeclareStatic = myDeclareStaticCb.isSelected();
    super.doOKAction();
  }
}
