// Copyright 2000-2019 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
package com.intellij.lang.javascript.flex.wizard;

import com.intellij.flex.model.bc.OutputType;
import com.intellij.flex.model.bc.TargetPlatform;
import com.intellij.lang.javascript.flex.FlexBundle;
import com.intellij.lang.javascript.flex.FlexModuleBuilder;
import com.intellij.lang.javascript.flex.projectStructure.options.BCUtils;
import com.intellij.lang.javascript.flex.sdk.FlexSdkComboBoxWithBrowseButton;
import com.intellij.lang.javascript.flex.sdk.FlexSdkUtils;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.projectRoots.Sdk;
import com.intellij.openapi.util.io.FileUtilRt;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.ui.NonFocusableCheckBox;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ui.UIUtil;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FlexModuleWizardForm {

  private final JPanel myMainPanel;
  private final JComboBox myTargetPlatformCombo;
  private final NonFocusableCheckBox myPureActionScriptCheckBox;
  private final JComboBox myOutputTypeCombo;

  private final JLabel myTargetDevicesLabel;
  private final JCheckBox myAndroidCheckBox;
  private final JCheckBox myIOSCheckBox;

  private final JLabel mySdkLabel;
  private final FlexSdkComboBoxWithBrowseButton mySdkCombo;

  private final JLabel myTargetPlayerLabel;
  private final JComboBox myTargetPlayerCombo;

  private final JCheckBox mySampleAppCheckBox;
  private final JTextField mySampleAppTextField;

  private final JCheckBox myHtmlWrapperCheckBox;
  private final JCheckBox myEnableHistoryCheckBox;
  private final JCheckBox myCheckPlayerVersionCheckBox;
  private final JCheckBox myExpressInstallCheckBox;

  public FlexModuleWizardForm() {
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myMainPanel = new JPanel();
      myMainPanel.setLayout(new GridLayoutManager(14, 4, new Insets(0, 0, 0, 0), -1, -1));
      final Spacer spacer1 = new Spacer();
      myMainPanel.add(spacer1, new GridConstraints(13, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      final JLabel label1 = new JLabel();
      label1.setText("Target platform:");
      label1.setDisplayedMnemonic('G');
      label1.setDisplayedMnemonicIndex(3);
      myMainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      myTargetPlatformCombo = new JComboBox();
      final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
      defaultComboBoxModel1.addElement("Web");
      myTargetPlatformCombo.setModel(defaultComboBoxModel1);
      myMainPanel.add(myTargetPlatformCombo, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                                 GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                 GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                 null, null, null, 0, false));
      myPureActionScriptCheckBox = new NonFocusableCheckBox();
      myPureActionScriptCheckBox.setText("Pure ActionScript");
      myPureActionScriptCheckBox.setMnemonic('U');
      myPureActionScriptCheckBox.setDisplayedMnemonicIndex(1);
      myMainPanel.add(myPureActionScriptCheckBox, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                      GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                      GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                      GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                      GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
      final JLabel label2 = new JLabel();
      label2.setText("Output type:");
      label2.setDisplayedMnemonic('O');
      label2.setDisplayedMnemonicIndex(0);
      myMainPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                  GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                  false));
      myOutputTypeCombo = new JComboBox();
      final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
      defaultComboBoxModel2.addElement("Application");
      myOutputTypeCombo.setModel(defaultComboBoxModel2);
      myMainPanel.add(myOutputTypeCombo, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                             GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                             GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer2 = new Spacer();
      myMainPanel.add(spacer2, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      mySampleAppCheckBox = new JCheckBox();
      mySampleAppCheckBox.setText("Create sample app:");
      mySampleAppCheckBox.setMnemonic('S');
      mySampleAppCheckBox.setDisplayedMnemonicIndex(7);
      myMainPanel.add(mySampleAppCheckBox, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                               GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myTargetPlayerLabel = new JLabel();
      myTargetPlayerLabel.setText("Target player:");
      myTargetPlayerLabel.setDisplayedMnemonic('T');
      myTargetPlayerLabel.setDisplayedMnemonicIndex(0);
      myMainPanel.add(myTargetPlayerLabel, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                               GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null,
                                                               null, null, 0, false));
      myTargetPlayerCombo = new JComboBox();
      myMainPanel.add(myTargetPlayerCombo, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                               GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      mySampleAppTextField = new JTextField();
      myMainPanel.add(mySampleAppTextField, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0,
                                                                false));
      final Spacer spacer3 = new Spacer();
      myMainPanel.add(spacer3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
      final Spacer spacer4 = new Spacer();
      myMainPanel.add(spacer4, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
      mySdkLabel = new JLabel();
      mySdkLabel.setText("Flex/AIR SDK:");
      mySdkLabel.setDisplayedMnemonic('K');
      mySdkLabel.setDisplayedMnemonicIndex(11);
      myMainPanel.add(mySdkLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                      GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null,
                                                      0, false));
      mySdkCombo = new FlexSdkComboBoxWithBrowseButton();
      myMainPanel.add(mySdkCombo, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                      GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                      GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                      null, null, 0, false));
      final Spacer spacer5 = new Spacer();
      myMainPanel.add(spacer5, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 10), null, 0, false));
      myTargetDevicesLabel = new JLabel();
      myTargetDevicesLabel.setText("Target devices:");
      myMainPanel.add(myTargetDevicesLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null,
                                                                null, null, 0, false));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
      myMainPanel.add(panel1, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                                  null, 0, false));
      myAndroidCheckBox = new JCheckBox();
      myAndroidCheckBox.setText("Android");
      myAndroidCheckBox.setMnemonic('A');
      myAndroidCheckBox.setDisplayedMnemonicIndex(0);
      panel1.add(myAndroidCheckBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer6 = new Spacer();
      panel1.add(spacer6, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                              GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      myIOSCheckBox = new JCheckBox();
      myIOSCheckBox.setText("iOS");
      myIOSCheckBox.setMnemonic('I');
      myIOSCheckBox.setDisplayedMnemonicIndex(0);
      panel1.add(myIOSCheckBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                    GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myEnableHistoryCheckBox = new JCheckBox();
      myEnableHistoryCheckBox.setText("Enable integration with browser navigation");
      myEnableHistoryCheckBox.setMnemonic('E');
      myEnableHistoryCheckBox.setDisplayedMnemonicIndex(0);
      myMainPanel.add(myEnableHistoryCheckBox, new GridConstraints(10, 0, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                   GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                   null, null, null, 2, false));
      myCheckPlayerVersionCheckBox = new JCheckBox();
      myCheckPlayerVersionCheckBox.setText("Check Flash player version");
      myCheckPlayerVersionCheckBox.setMnemonic('V');
      myCheckPlayerVersionCheckBox.setDisplayedMnemonicIndex(19);
      myMainPanel.add(myCheckPlayerVersionCheckBox, new GridConstraints(11, 0, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                        GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                        GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 2, false));
      myExpressInstallCheckBox = new JCheckBox();
      myExpressInstallCheckBox.setText("Express install");
      myExpressInstallCheckBox.setMnemonic('X');
      myExpressInstallCheckBox.setDisplayedMnemonicIndex(1);
      myMainPanel.add(myExpressInstallCheckBox, new GridConstraints(12, 0, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                    GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                    GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                    null, null, null, 4, false));
      myHtmlWrapperCheckBox = new JCheckBox();
      myHtmlWrapperCheckBox.setText("Create HTML wrapper template");
      myHtmlWrapperCheckBox.setMnemonic('R');
      myHtmlWrapperCheckBox.setDisplayedMnemonicIndex(1);
      myMainPanel.add(myHtmlWrapperCheckBox, new GridConstraints(9, 0, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                 GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                 GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                 null, null, null, 0, false));
      label1.setLabelFor(myTargetPlatformCombo);
      label2.setLabelFor(myOutputTypeCombo);
      myTargetPlayerLabel.setLabelFor(myTargetPlayerCombo);
    }
    mySdkLabel.setLabelFor(mySdkCombo.getChildComponent());
    BCUtils.initTargetPlatformCombo(myTargetPlatformCombo);
    BCUtils.initOutputTypeCombo(myOutputTypeCombo);

    final ActionListener listener = new ActionListener() {
      @Override
      public void actionPerformed(final ActionEvent e) {
        updateControls();
      }
    };

    myTargetPlatformCombo.addActionListener(listener);
    myOutputTypeCombo.addActionListener(listener);
    mySampleAppCheckBox.addActionListener(listener);
    myHtmlWrapperCheckBox.addActionListener(listener);
    myCheckPlayerVersionCheckBox.addActionListener(listener);

    mySdkCombo.addComboboxListener(new FlexSdkComboBoxWithBrowseButton.Listener() {
      @Override
      public void stateChanged() {
        BCUtils.updateAvailableTargetPlayers(mySdkCombo.getSelectedSdk(), myTargetPlayerCombo);
        updateControls();
      }
    });

    myPureActionScriptCheckBox.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(final ActionEvent e) {
        final String sampleApp = mySampleAppTextField.getText().trim();
        if (sampleApp.endsWith(".as") || sampleApp.endsWith(".mxml")) {
          mySampleAppTextField
            .setText(FileUtilRt.getNameWithoutExtension(sampleApp) + (myPureActionScriptCheckBox.isSelected() ? ".as" : ".mxml"));
        }
      }
    });

    reset();
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myMainPanel; }

  public JPanel getMainPanel() {
    return myMainPanel;
  }

  public void setEnabled(final boolean enabled) {
    UIUtil.setEnabled(myMainPanel, enabled, true);
    if (enabled) {
      updateControls();
    }
  }

  private void reset() {
    myTargetPlayerCombo.setSelectedItem(TargetPlatform.Web);
    myPureActionScriptCheckBox.setSelected(false);
    myOutputTypeCombo.setSelectedItem(OutputType.Application);
    myAndroidCheckBox.setSelected(true);
    myIOSCheckBox.setSelected(true);
    BCUtils.updateAvailableTargetPlayers(mySdkCombo.getSelectedSdk(), myTargetPlayerCombo);
    mySampleAppCheckBox.setSelected(true);
    mySampleAppTextField.setText("Main.mxml");
    myHtmlWrapperCheckBox.setSelected(true);
    myEnableHistoryCheckBox.setSelected(true);
    myCheckPlayerVersionCheckBox.setSelected(true);
    myExpressInstallCheckBox.setSelected(true);

    updateControls();
  }

  private void updateControls() {
    final Sdk sdk = mySdkCombo.getSelectedSdk();
    final boolean sdkSet = sdk != null;
    final boolean web = myTargetPlatformCombo.getSelectedItem() == TargetPlatform.Web;
    final boolean mobile = myTargetPlatformCombo.getSelectedItem() == TargetPlatform.Mobile;
    final boolean app = myOutputTypeCombo.getSelectedItem() == OutputType.Application;

    final boolean createSampleAppWasEnabled = mySampleAppCheckBox.isEnabled();
    final boolean createHtmlWrapperWasEnabled = myHtmlWrapperCheckBox.isEnabled();
    final boolean targetDeviceWasEnabled = myTargetDevicesLabel.isEnabled();

    myTargetDevicesLabel.setEnabled(mobile && app);
    myAndroidCheckBox.setEnabled(mobile && app);
    myIOSCheckBox.setEnabled(mobile && app);

    myTargetPlayerLabel.setEnabled(web && sdkSet);
    myTargetPlayerCombo.setEnabled(web && sdkSet);

    mySampleAppCheckBox.setEnabled(app && sdkSet);
    mySampleAppTextField.setEnabled(app && sdkSet);

    myHtmlWrapperCheckBox.setEnabled(web && app && sdkSet);

    if (myTargetDevicesLabel.isEnabled() && !targetDeviceWasEnabled) {
      myAndroidCheckBox.setSelected(true);
      myIOSCheckBox.setSelected(true);
    }

    if (!myTargetDevicesLabel.isEnabled()) {
      // disabled but checked for mobile library
      myAndroidCheckBox.setSelected(mobile);
      myIOSCheckBox.setSelected(mobile);
    }

    if (!mySampleAppCheckBox.isEnabled() || !createSampleAppWasEnabled) {
      mySampleAppCheckBox.setSelected(mySampleAppCheckBox.isEnabled());
    }

    mySampleAppTextField.setEnabled(mySampleAppCheckBox.isEnabled() && mySampleAppCheckBox.isSelected());

    if (!myHtmlWrapperCheckBox.isEnabled() || !createHtmlWrapperWasEnabled) {
      myHtmlWrapperCheckBox.setSelected(myHtmlWrapperCheckBox.isEnabled());
    }

    myEnableHistoryCheckBox.setEnabled(myHtmlWrapperCheckBox.isSelected() && web && app);
    myCheckPlayerVersionCheckBox.setEnabled(myHtmlWrapperCheckBox.isSelected() && web && app);
    myExpressInstallCheckBox.setEnabled(myHtmlWrapperCheckBox.isSelected() && myCheckPlayerVersionCheckBox.isSelected() && web && app);
  }

  public void applyTo(final FlexModuleBuilder moduleBuilder) {
    moduleBuilder.setTargetPlatform((TargetPlatform)myTargetPlatformCombo.getSelectedItem());
    moduleBuilder.setPureActionScript(myPureActionScriptCheckBox.isSelected());
    moduleBuilder.setOutputType((OutputType)myOutputTypeCombo.getSelectedItem());
    moduleBuilder.setAndroidEnabled(myAndroidCheckBox.isSelected());
    moduleBuilder.setIOSEnabled(myIOSCheckBox.isSelected());
    moduleBuilder.setFlexSdk(mySdkCombo.getSelectedSdk());
    moduleBuilder.setTargetPlayer((String)myTargetPlayerCombo.getSelectedItem());
    moduleBuilder.setCreateSampleApp(mySampleAppCheckBox.isEnabled() && mySampleAppCheckBox.isSelected());
    moduleBuilder.setSampleAppName(mySampleAppTextField.getText().trim());
    moduleBuilder.setCreateHtmlWrapperTemplate(myHtmlWrapperCheckBox.isEnabled() && myHtmlWrapperCheckBox.isSelected());
    moduleBuilder.setHtmlWrapperTemplateParameters(myEnableHistoryCheckBox.isSelected(), myCheckPlayerVersionCheckBox.isSelected(),
                                                   myExpressInstallCheckBox.isEnabled() && myExpressInstallCheckBox.isSelected());
  }

  public boolean validate() throws ConfigurationException {
    final Sdk sdk = mySdkCombo.getSelectedSdk();
    if (sdk != null) {

      if (myTargetPlatformCombo.getSelectedItem() == TargetPlatform.Mobile &&
          !FlexSdkUtils.isAirSdkWithoutFlex(sdk) &&
          StringUtil.compareVersionNumbers(sdk.getVersionString(), "4.5") < 0) {
        throw new ConfigurationException(FlexBundle.message("sdk.does.not.support.air.mobile", sdk.getVersionString()));
      }

      if (FlexSdkUtils.isAirSdkWithoutFlex(sdk) && !myPureActionScriptCheckBox.isSelected()) {
        throw new ConfigurationException(StringUtil.capitalize(FlexBundle.message("air.sdk.requires.pure.as", sdk.getName())));
      }

      if (mySampleAppCheckBox.isSelected()) {
        final String fileName = mySampleAppTextField.getText().trim();
        if (fileName.isEmpty()) {
          throw new ConfigurationException(FlexBundle.message("sample.app.name.empty"));
        }

        final String extension = StringUtil.toLowerCase(FileUtilRt.getExtension(fileName));
        if (!"mxml".equals(extension) && !"as".equals(extension)) {
          throw new ConfigurationException(FlexBundle.message("sample.app.incorrect.extension"));
        }
      }
    }

    return true;
  }
}
