/*
 * Copyright (C) 2020 ThoughtWorks, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.thoughtworks.gauge.rename;

import com.intellij.openapi.editor.Editor;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.psi.PsiFile;
import com.intellij.ui.EditorTextField;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.thoughtworks.gauge.GaugeBundle;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.Nullable;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;

public final class RefactoringDialog extends DialogWrapper {
  private final EditorTextField inputText;
  private final JPanel contentPane;
  private final JLabel heading;
  private final JLabel infoPane;

  private final Project project;
  private final PsiFile file;
  private final Editor editor;
  private final String text;

  @Override
  public @Nullable JComponent getPreferredFocusedComponent() {
    return inputText;
  }

  public RefactoringDialog(Project project, PsiFile file, Editor editor, String text) {
    super(project);
    this.project = project;
    this.file = file;
    this.editor = editor;
    this.text = text;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      contentPane = new JPanel();
      contentPane.setLayout(new GridLayoutManager(3, 3, new Insets(5, 5, 5, 5), -1, -1));
      contentPane.setEnabled(false);
      contentPane.setMinimumSize(new Dimension(400, 75));
      contentPane.setPreferredSize(new Dimension(400, 75));
      contentPane.setRequestFocusEnabled(false);
      contentPane.setVisible(true);
      inputText = new EditorTextField();
      contentPane.add(inputText, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
                                                     GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      infoPane = new JLabel();
      infoPane.setText("");
      infoPane.setVisible(false);
      contentPane.add(infoPane, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                    GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                                    false));
      heading = new JLabel();
      heading.setEnabled(true);
      heading.setFocusable(false);
      heading.setText("");
      contentPane.add(heading, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                   GridConstraints.SIZEPOLICY_FIXED, new Dimension(380, -1), null, null, 0, false));
    }
    setModal(true);
    setTitle(GaugeBundle.message("gauge.group.refactoring"));
    this.heading.setText(GaugeBundle.message("refactoring.to", this.text));
    this.inputText.setText(this.text);
    setSize();
    registerActions();
    repaint();
    init();
    addListeners();
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return contentPane; }

  private void registerActions() {
    this.contentPane.registerKeyboardAction(e -> doOKAction(), KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),
                                            JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
  }

  private void addListeners() {
    addResizeListener();
    addInputFocusListener();
  }

  private void addResizeListener() {
    final ComponentAdapter resizeListener = new ComponentAdapter() {
      @Override
      public void componentResized(ComponentEvent event) {
        Dimension contentSize = contentPane.getSize();
        Dimension componentSize = event.getComponent().getSize();
        if (componentSize.getWidth() > contentSize.getWidth()) {
          event.getComponent().setSize(new Dimension((int)contentSize.getWidth() - 20, (int)componentSize.getHeight()));
        }
      }
    };
    this.inputText.addComponentListener(resizeListener);
    this.heading.addComponentListener(resizeListener);
  }

  private void addInputFocusListener() {
    inputText.addFocusListener(new FocusAdapter() {
      @Override
      public void focusGained(FocusEvent e) {
        inputText.removeSelection();
        inputText.setCaretPosition(0);
      }
    });
  }

  @Override
  protected void doOKAction() {
    setOKActionEnabled(false);
    this.infoPane.setEnabled(true);
    this.infoPane.setVisible(true);
    String inputString = inputText.getText();
    new GaugeRefactorHandler(project, file, editor).compileAndRefactor(text, inputString, new RefactorStatusCallback() {
      @Override
      public void onStatusChange(@Nls String statusMessage) {
        infoPane.setText(statusMessage);
      }

      @Override
      public void onFinish(RefactoringStatus refactoringStatus) {
        if (refactoringStatus.isPassed()) {
          doCancelAction();
        }
        else {
          getRootPane().setDefaultButton(getButton(myCancelAction));
          infoPane.setVisible(false);
          setErrorText(refactoringStatus.getErrorMessage());
        }
      }
    });
  }

  @Override
  public void doCancelAction() {
    this.getWindow().setVisible(false);
    dispose();
  }

  @Override
  protected @Nullable JComponent createCenterPanel() {
    return contentPane;
  }

  private void setSize() {
    int stringWidth = SwingUtilities.computeStringWidth(this.heading.getFontMetrics(this.heading.getFont()), this.heading.getText());
    int height = this.contentPane.getHeight();
    this.contentPane.setSize(new Dimension(stringWidth + 30, height));
    this.contentPane.setMinimumSize(new Dimension(stringWidth + 30, height));
  }
}
