/*
 * Copyright 2000-2015 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package jetbrains.plugins.yeoman.projectGenerator.ui.list;

import com.intellij.psi.codeStyle.NameUtil;
import com.intellij.ui.JBColor;
import com.intellij.ui.SimpleColoredComponent;
import com.intellij.ui.SimpleTextAttributes;
import com.intellij.ui.components.JBLabel;
import com.intellij.ui.speedSearch.SpeedSearchSupply;
import com.intellij.ui.speedSearch.SpeedSearchUtil;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.util.text.Matcher;
import com.intellij.util.text.matching.MatchingMode;
import com.intellij.util.ui.JBUI;
import com.intellij.util.ui.StartupUiUtil;
import com.intellij.util.ui.UIUtil;
import jetbrains.plugins.yeoman.generators.YeomanGeneratorInfo;

import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Insets;

public final class YeomanGeneratorCellRenderer extends DefaultTableCellRenderer {
  private final YeomanGeneratorInfo myInfo;

  private final JPanel myPanel;
  private final SimpleColoredComponent myName;
  private final JPanel myInfoPanel;
  private final JBLabel myStatus;

  public YeomanGeneratorCellRenderer(YeomanGeneratorInfo info) {
    myInfo = info;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myPanel = new JPanel();
      myPanel.setLayout(new BorderLayout(0, 0));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
      panel1.setOpaque(false);
      myPanel.add(panel1, BorderLayout.WEST);
      panel1.setBorder(
        BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 3, 0, 6), null, TitledBorder.DEFAULT_JUSTIFICATION,
                                         TitledBorder.DEFAULT_POSITION, null, null));
      myStatus = new JBLabel();
      myStatus.setText("");
      panel1.add(myStatus,
                 new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myInfoPanel = new JPanel();
      myInfoPanel.setLayout(new BorderLayout(0, 0));
      myInfoPanel.setOpaque(false);
      myPanel.add(myInfoPanel, BorderLayout.CENTER);
      final JPanel panel2 = new JPanel();
      panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
      panel2.setOpaque(false);
      myInfoPanel.add(panel2, BorderLayout.NORTH);
      panel2.setBorder(
        BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 2, 0), null, TitledBorder.DEFAULT_JUSTIFICATION,
                                         TitledBorder.DEFAULT_POSITION, null, null));
      myName = new SimpleColoredComponent();
      panel2.add(myName, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                             GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                             GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null,
                                             0, false));
    }
    myName.setFont(StartupUiUtil.getLabelFont());

    myPanel.setBorder(UIUtil.isRetina() ? JBUI.Borders.empty(2, 1) : JBUI.Borders.empty(1));
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myPanel; }


  @Override
  public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
    if (myInfo != null) {
      Color fg = UIUtil.getTableForeground(isSelected, hasFocus);
      Color bg = UIUtil.getTableBackground(isSelected, hasFocus);

      myPanel.setBackground(bg);

      myName.setForeground(fg);

      myName.clear();
      myName.setOpaque(false);
      String generatorName = myInfo.getYoName() + "  ";
      Object query = table.getClientProperty(SpeedSearchSupply.SEARCH_QUERY_KEY);
      SimpleTextAttributes attr = new SimpleTextAttributes(UIUtil.getListBackground(isSelected, hasFocus),
                                                           UIUtil.getListForeground(isSelected, hasFocus),
                                                           JBColor.RED,
                                                           SimpleTextAttributes.STYLE_PLAIN);
      Matcher matcher = NameUtil.buildMatcher("*" + query, MatchingMode.IGNORE_CASE);
      if (query instanceof String) {
        SpeedSearchUtil.appendColoredFragmentForMatcher(generatorName, myName, attr, matcher,
                                                        UIUtil.getTableBackground(isSelected, hasFocus), true);
      }
      else {
        myName.append(generatorName);
      }
    }
    return myPanel;
  }
}
