package jetbrains.plugins.yeoman.projectGenerator.ui.list;

import com.intellij.ide.ui.search.SearchUtil;
import com.intellij.openapi.Disposable;
import com.intellij.openapi.actionSystem.ActionGroup;
import com.intellij.openapi.actionSystem.ActionManager;
import com.intellij.openapi.actionSystem.ActionToolbar;
import com.intellij.openapi.ui.Splitter;
import com.intellij.openapi.util.NlsSafe;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.ui.BrowserHyperlinkListener;
import com.intellij.ui.FilterComponent;
import com.intellij.ui.Gray;
import com.intellij.ui.GuiUtils;
import com.intellij.ui.JBColor;
import com.intellij.ui.ScrollPaneFactory;
import com.intellij.ui.TableUtil;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.ui.scale.JBUIScale;
import com.intellij.ui.speedSearch.SpeedSearchSupply;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ArrayUtil;
import com.intellij.util.ui.JBUI;
import com.intellij.util.ui.UIUtil;
import jetbrains.plugins.yeoman.generators.YeomanGeneratorFullInfo;
import jetbrains.plugins.yeoman.generators.YeomanGeneratorInfo;
import jetbrains.plugins.yeoman.generators.YeomanInstalledGeneratorInfo;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JEditorPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.BorderUIResource;
import javax.swing.text.html.HTMLEditorKit;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Insets;

public class YeomanGeneratorsMain implements Disposable {

  private static final @NlsSafe String TEXT_SUFFIX = "</body></html>";

  protected final JPanel main;
  protected final JPanel myToolbarPanel;
  protected final JEditorPane myDescriptionTextArea;
  protected final JPanel myInfoPanel;
  protected final JPanel myTablePanel;
  protected final JBScrollPane myDescriptionScrollPane;
  protected final JPanel myHeader;
  private final JSplitPane mySplitPane;
  protected YeomanGeneratorTable myGeneratorTable;

  protected @Nullable MyPluginsFilter myFilter;

  private YeomanGeneratorInfoPanelHeader myGeneratorInfoPanelHeader;
  private ActionToolbar myActionToolbar;

  public YeomanGeneratorTableModel getModel() {
    return myModel;
  }

  protected YeomanGeneratorTableModel myModel;


  public YeomanGeneratorsMain() {
    {
      myHeader = new JPanel(new BorderLayout()) {
        @Override
        public Color getBackground() {
          return UIUtil.getTextFieldBackground();
        }
      };
    }
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      main = new JPanel();
      main.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
      main.setPreferredSize(new Dimension(550, 205));
      main.setRequestFocusEnabled(true);
      final Spacer spacer1 = new Spacer();
      main.add(spacer1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                            GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      myToolbarPanel = new JPanel();
      myToolbarPanel.setLayout(new BorderLayout(0, 0));
      main.add(myToolbarPanel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL,
                                                   GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null,
                                                   0, false));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
      main.add(panel1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                           GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null,
                                           0, false));
      mySplitPane = new JSplitPane();
      mySplitPane.setContinuousLayout(true);
      mySplitPane.setDividerSize(2);
      mySplitPane.setEnabled(false);
      mySplitPane.setOneTouchExpandable(false);
      panel1.add(mySplitPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                                  null, 0, false));
      mySplitPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION,
                                                             TitledBorder.DEFAULT_POSITION, null, null));
      myInfoPanel = new JPanel();
      myInfoPanel.setLayout(new BorderLayout(0, 0));
      myInfoPanel.setMinimumSize(new Dimension(50, 50));
      myInfoPanel.setPreferredSize(new Dimension(300, 200));
      mySplitPane.setRightComponent(myInfoPanel);
      myDescriptionScrollPane = new JBScrollPane();
      myInfoPanel.add(myDescriptionScrollPane, BorderLayout.CENTER);
      myDescriptionScrollPane.setBorder(
        BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION,
                                         TitledBorder.DEFAULT_POSITION, null, null));
      myDescriptionTextArea = new JEditorPane();
      myDescriptionTextArea.setContentType("text/html");
      myDescriptionTextArea.setEditable(false);
      myDescriptionTextArea.setMargin(new Insets(0, 0, 0, 0));
      myDescriptionTextArea.setMaximumSize(new Dimension(-1, -1));
      myDescriptionTextArea.putClientProperty("JEditorPane.honorDisplayProperties", Boolean.TRUE);
      myDescriptionScrollPane.setViewportView(myDescriptionTextArea);
      myInfoPanel.add(myHeader, BorderLayout.NORTH);
      myHeader.setBorder(
        BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 10, 0, 6), null, TitledBorder.DEFAULT_JUSTIFICATION,
                                         TitledBorder.DEFAULT_POSITION, null, null));
      myTablePanel = new JPanel();
      myTablePanel.setLayout(new BorderLayout(0, 0));
      myTablePanel.setMinimumSize(new Dimension(50, 50));
      myTablePanel.setPreferredSize(new Dimension(300, 200));
      mySplitPane.setLeftComponent(myTablePanel);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return main; }

  protected void init(boolean isFullInfo) {
    GuiUtils.replaceJSplitPaneWithIDEASplitter(main);
    myDescriptionTextArea.setEditorKit(new HTMLEditorKit());
    myDescriptionTextArea.setEditable(false);
    myDescriptionTextArea.addHyperlinkListener(new BrowserHyperlinkListener());
    myDescriptionTextArea.setBorder(JBUI.Borders.emptyLeft(5));
    myModel = new YeomanGeneratorTableModel();

    myGeneratorTable = new YeomanGeneratorTable(myModel);

    JScrollPane scrollpanel = ScrollPaneFactory
      .createScrollPane(myGeneratorTable, ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED,
                        ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    myTablePanel.add(scrollpanel, BorderLayout.CENTER);


    myDescriptionScrollPane.setBackground(UIUtil.getTextFieldBackground());
    Border border = new BorderUIResource.LineBorderUIResource(new JBColor(Gray._220, Gray._55), 1);
    myInfoPanel.setBorder(border);

    myGeneratorInfoPanelHeader = new YeomanGeneratorInfoPanelHeader(this, isFullInfo);


    myHeader.setBackground(UIUtil.getTextFieldBackground());
    myHeader.add(myGeneratorInfoPanelHeader.getComponent(), BorderLayout.CENTER);

    installTableActions();

    if (myFilter != null) {
      myToolbarPanel.add(myFilter, BorderLayout.WEST);
    }

    final ActionGroup group = getActionGroup(true);
    if (group != null) {
      myActionToolbar = ActionManager.getInstance().createActionToolbar("YeomanGenerators", group, true);
      final JComponent component = myActionToolbar.getComponent();
      component.setBorder(JBUI.Borders.emptyBottom(6));
      myToolbarPanel.add(component, BorderLayout.CENTER);
    }

    final Container parent = myInfoPanel.getParent();
    if (parent instanceof Splitter) {
      ((Splitter)parent).setDividerWidth(2);
    }
  }

  protected ActionGroup getActionGroup(boolean b) {
    return null;
  }


  @Override
  public void dispose() {

  }

  public void repaint() {
    myModel.fireTableDataChanged();
  }

  protected void installTableActions() {
    YeomanGeneratorSpeedSearch.installOn(myGeneratorTable);

    myGeneratorTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
      @Override
      public void valueChanged(ListSelectionEvent e) {
        refresh();
      }
    });
  }

  private void refresh() {
    YeomanGeneratorInfo selectedValue = getSelectedValue();
    final YeomanGeneratorFullInfo generator = getFullGeneratorInfo(selectedValue);
    setTextValue(generator == null ? null : new StringBuilder(generator.getDescription()), null, myDescriptionTextArea);
    myGeneratorInfoPanelHeader.updateInfo(selectedValue);
    final JComponent parent = (JComponent)myHeader.getParent();
    parent.revalidate();
    parent.repaint();
  }


  private @Nullable YeomanGeneratorInfo getSelectedValue() {
    YeomanGeneratorInfo[] descriptors = myGeneratorTable.getSelectedObjects();
    return descriptors != null && descriptors.length == 1 ? descriptors[0] : null;
  }

  private static @NlsSafe String getTextPrefix() {
    final int fontSize = JBUIScale.scale(13);
    final int m1 = JBUIScale.scale(1);
    final int m2 = JBUIScale.scale(5);

    return String.format(
      "<html><head>" +
      "    <style type=\"text/css\">" +
      "        p {" +
      "            font-family: Arial,serif; font-size: %dpt; margin: %dpx %dpx" +
      "        }" +
      "    </style>" +
      "</head><body style=\"font-family: Arial,serif; font-size: %dpt; margin: %dpx %dpx;\">",
      fontSize, m1, m1, fontSize, m2, m2);
  }

  public static void setTextValue(@Nls @NlsSafe StringBuilder text, @Nullable String filter, JEditorPane pane) {
    if (text != null) {
      text.insert(0, getTextPrefix());
      text.append(TEXT_SUFFIX);
      @NlsSafe String trim = SearchUtil.markup(text.toString(), filter).trim();
      pane.setText(trim);
      pane.setCaretPosition(0);
    }
    else {
      pane.setText(getTextPrefix() + TEXT_SUFFIX);
    }
  }


  public @NotNull JPanel getMainPanel() {
    return main;
  }

  @SuppressWarnings("unused")
  public @Nullable YeomanGeneratorInfo getSelectedObject() {
    return ArrayUtil.getFirstElement(myGeneratorTable.getSelectedObjects());
  }

  public void handleUpdate() {
  }


  public class MyPluginsFilter extends FilterComponent {
    public MyPluginsFilter() {
      super("PLUGIN_FILTER", 5);
    }

    @Override
    public void filter() {
      myGeneratorTable.putClientProperty(SpeedSearchSupply.SEARCH_QUERY_KEY, getFilter());
      myModel.filter(getFilterLowerCase());
      TableUtil.ensureSelectionExists(myGeneratorTable);
    }

    public String getFilterLowerCase() {
      return StringUtil.toLowerCase(getFilter());
    }
  }

  public void select(@Nullable YeomanGeneratorInfo info) {
    myGeneratorTable.select(info);
  }

  public @Nullable YeomanInstalledGeneratorInfo getInstalledGeneratorInfo(YeomanGeneratorInfo info) {
    return info instanceof YeomanInstalledGeneratorInfo ? (YeomanInstalledGeneratorInfo)info : null;
  }

  public @Nullable YeomanGeneratorFullInfo getFullGeneratorInfo(@Nullable YeomanGeneratorInfo info) {
    return YeomanGeneratorFullInfo.getFullInfo(info);
  }
}
